### polynomial regression
- 직선으로 많은 데이터를 만족할 수 없는 liear-regression의 경우 사용
- 기존의 feature를 조합해서 항을 늘여주는 작업진행 ==> preprocessing에서 사용

In [1]:
from sklearn.preprocessing import PolynomialFeatures

In [2]:
import numpy as np

In [5]:
# create randomly data
X = np.arange(4)
X = X.reshape(-1, 2)
X

array([[0, 1],
       [2, 3]])

In [28]:
# feature 2개를 조합해서 늘이기
poly = PolynomialFeatures()

X1 = poly.fit_transform(X)

X1

array([[1., 0., 1., 0., 0., 1.],
       [1., 2., 3., 4., 6., 9.]])

In [29]:
poly.get_feature_names_out()

array(['1', 'x0', 'x1', 'x0^2', 'x0 x1', 'x1^2'], dtype=object)

In [9]:
# feature 2개를 조합해서 늘이기
poly = PolynomialFeatures(include_bias=False, degree=4)

X2 = poly.fit_transform(X)

X2

array([[ 0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         1.],
       [ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27., 16., 24., 36., 54.,
        81.]])

In [10]:
poly.get_feature_names_out()

array(['x0', 'x1', 'x0^2', 'x0 x1', 'x1^2', 'x0^3', 'x0^2 x1', 'x0 x1^2',
       'x1^3', 'x0^4', 'x0^3 x1', 'x0^2 x1^2', 'x0 x1^3', 'x1^4'],
      dtype=object)

In [15]:
X2.shape

(2, 14)

In [20]:
# feature 2개를 조합해서 늘이기
x = np.arange(10).reshape(-1, 2)

poly = PolynomialFeatures(include_bias=False, degree=5)

X3 = poly.fit_transform(x)

X3.shape


(5, 20)

In [31]:
y = 1 + 2*X1[:,0] + 3*X1[:,0]**2 + 4*X1[:,0]**3

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
model = LinearRegression()

In [32]:
model.fit(X1, y)

LinearRegression()

In [23]:
from sklearn.pipeline import Pipeline

In [33]:
pipe = Pipeline([('poly', poly), ('lrmodel', model)])

pipe.fit(X1, y)

Pipeline(steps=[('poly', PolynomialFeatures()),
                ('lrmodel', LinearRegression())])

In [34]:
pipe.named_steps['lrmodel'].coef_       # coef_: weight, gredient

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [35]:
pipe.named_steps['poly'].degree     # degree: 차수

2