### 넘파이 Chapter 1
- 배열(Array) 구조 이해하기
- 넘파이 모듈의 함수 특징
- 배열과 할당 검색

In [1]:
import numpy as np

- 배열(Array) 구조 이해하기
    - 파이썬 리스트 구조 이해하기

In [2]:
# 예제1 리스트 구조
l = [[1, 2, 3], [4, 5, 6]]
print(type(l))

<class 'list'>


In [3]:
print(l[0])     # 리스트의 인덱스는 0번째부터
print(l[1])

[1, 2, 3]
[4, 5, 6]


In [4]:
# 리스트 안의 리스트 요소까지 다 꺼내는
for i, a in enumerate(l):
    for j, b in enumerate(a):
        print(l[i][j])

1
2
3
4
5
6


- 배열(Array) 구조 이해하기
    - 다차원 배열의 구조 이해하기

In [5]:
np.__version__

'2.0.1'

In [6]:
print(np.ndarray)

<class 'numpy.ndarray'>


In [7]:
np.ndarray.__name__

'ndarray'

In [8]:
# np.ndarray 클래스의 이름 딕셔너리?
for i in dir(np.ndarray):
    if not i.startswith("_"):
        if type(np.ndarray.__dict__[i]) != type(np.ndarray.var):
            print(i)

T
base
ctypes
data
device
dtype
flags
flat
imag
itemset
itemsize
mT
nbytes
ndim
newbyteorder
ptp
real
shape
size
strides


In [9]:
# 넘파이 배열 생성하기
l = [1, 2, 3, 4]
a = np.array(l)
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [10]:
t = (1, 2, 3, 4)
b = np.array(t)
print(b)
print(type(b))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
print(a.data)
print(a.data.obj)
print(type(a.data.obj))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
c = b
c.base is b.base

True

In [13]:
c[0] = 100
print(c)    # 주소값이 같아서
print(b)

[100   2   3   4]
[100   2   3   4]


In [14]:
d = np.array(b)
d[0] = 99
print(b)
print(d)    # 이 경우는 주소값이 다르기 때문

[100   2   3   4]
[99  2  3  4]


In [15]:
e = np.array(l, dtype=np.float64)
print(e)
print(e.dtype)

[1. 2. 3. 4.]
float64


In [16]:
a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2.shape)
print(a2.ndim)
print(a2.dtype) # 책에서는 int32로 나옴

(2, 3)
2
int64


In [17]:
print(a2.itemsize)
print(a2.size)
print(a2.strides)   # int32가 아닌 int64라서 조금 다른듯

8
6
(24, 8)


In [18]:
print(a2.flatten())
print(a2.ravel())       # 2차원을 1차원으로 나타낼 수 있음

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [19]:
# 넘파이 배열 원소 조회하기
print(a)
print(l)    # 위에서 만들어둔 데이터 사용

[1 2 3 4]
[1, 2, 3, 4]


In [20]:
print(a[0])
print(l[0])

1
1


In [21]:
l2 = [[1, 2, 3], [4, 5, 6]]
print(l2)
print(a2)

[[1, 2, 3], [4, 5, 6]]
[[1 2 3]
 [4 5 6]]


In [22]:
# 다차원 배열을 조회하는 방법: 색인연산자 사용
try:
    l2[0,1]
except Exception as e:
    print(e)

list indices must be integers or slices, not tuple


In [23]:
print(l2[0][1])
print(a2[0][1])

2
2


In [24]:
print(type(a2[0, 1]))
print(a2[0, 1].item())
print(type(a2[0, 1].item()))

<class 'numpy.int64'>
2
<class 'int'>


In [25]:
print(a2[0, 1].real)
print(a2[0, 1].imag)

2
0


- 배열(Array) 구조 이해하기
    - 다차원 배열 클래스의 자료구조

In [26]:
# 넘파이 모듈의 배열 내부구조 확인
na = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
na

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [27]:
print(na.ndim)
print(na.shape)

3
(2, 2, 3)


In [28]:
print(na[0])
print(na[0].shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [29]:
print(na.strides)
na.__array_interface__  # 딕셔너리 반환

(48, 24, 8)


{'data': (2321534720032, False),
 'strides': None,
 'descr': [('', '<i8')],
 'typestr': '<i8',
 'shape': (2, 2, 3),
 'version': 3}

In [30]:
print(na.__array_interface__['data'][0])    # 속성
print(len(na.data.tobytes()))   # 메소드
print(na.data.tolist())

2321534720032
96
[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]


In [31]:
# data 속성 관리 기준
a = np.array([1, 2, 3, 4])
print(a)
print(a.data)

[1 2 3 4]


In [32]:
mem = memoryview(a)
print(mem)

In [33]:
print(a.data[0])
print(a.data.obj)
print(a.data.obj[0])

1
[1 2 3 4]
1


In [34]:
print(a.dtype)
print(a.itemsize)
print(a.data.hex())

int64
8
0100000000000000020000000000000003000000000000000400000000000000


In [35]:
b = np.array([999, 9999, 99999, 999999])
print(b.data.hex()[:8])

e7030000


In [36]:
print(hex(999))
print(int('0x3e7', 16))

0x3e7
999


In [37]:
print(divmod(999, 16))
print(divmod(62, 16))
print(divmod(3, 16))

(62, 7)
(3, 14)
(0, 3)


In [38]:
print(a.size)
print()
for i in range(a.size):
    print(a[i])

4

1
2
3
4


In [39]:
print(a.flat)
print()
for i in a.flat:
    print(i)


1
2
3
4


In [40]:
c = np.array([1, 2, 3, 4], dtype=np.float64)
print(c)

[1. 2. 3. 4.]


In [41]:
x = np.frombuffer(c)
print(x)

[1. 2. 3. 4.]


In [42]:
print(x.data)
print(x[0])
print(x.flags)  # 배열의 정보

1.0
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [43]:
print(x.base is c)
print(c.flags)

True
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



- 배열(Array)의 구조 이해하기
    - 다차원 배열의 두 클래스 비교하기

In [44]:
# 두 클래스 비교
print(np.ndarray.__base__)
print(np.matrix.__base__)

<class 'object'>
<class 'numpy.ndarray'>


In [45]:
l1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(l1.shape)

(8,)


In [46]:
m1 = np.matrix([1, 2, 3, 4, 5, 6, 7, 8])
print(m1.shape)

(1, 8)


In [47]:
l2 = l1.reshape(2, 4)
print(l2.shape)

(2, 4)


In [48]:
m2 = m1.reshape(2, 4)   # 달라짐
print(m2.shape)

(2, 4)


In [49]:
l3 = l2.reshape(2, 2, 2)

try:
    m3 = m2.reshape(2, 2, 2)    # 2차원 행렬만 처리하기 때문
except Exception as e:
    print(e)

shape too large to be a matrix.


In [50]:
m2_1 = np.asmatrix(l1).reshape(2, 4)
m2_1

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [51]:
l2 * l2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [52]:
try:
    m2 * m2
except Exception as e:
    print(e)

shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)


In [53]:
np.multiply(m2, m2)

matrix([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])

In [54]:
np.multiply(l2, l2)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [55]:
# 두 클래스 차이점 확인
nd_ = set(dir(np.ndarray))
md_ = set(dir(np.matrix))
md_ - nd_

{'A',
 'A1',
 'H',
 'I',
 '__annotations__',
 '__dict__',
 '__module__',
 '_align',
 '_collapse',
 'getA',
 'getA1',
 'getH',
 'getI',
 'getT'}

In [56]:
m4 = np.asmatrix('1 2; 3 4')
m4

matrix([[1, 2],
        [3, 4]])

In [57]:
print(m4.A)
print(m4.getA())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [58]:
print(m4.H)
print(m4.T)

[[1 3]
 [2 4]]
[[1 3]
 [2 4]]


In [59]:
np.linalg.inv(m4)

matrix([[-2. ,  1. ],
        [ 1.5, -0.5]])

In [60]:
m4.T

matrix([[1, 3],
        [2, 4]])

In [61]:
m2

matrix([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [62]:
try:
    np.linalg.inv(m2)
except Exception as e:
    print(e)

Last 2 dimensions of the array must be square


In [63]:
m2.I

matrix([[-5.50000000e-01,  2.50000000e-01],
        [-2.25000000e-01,  1.25000000e-01],
        [ 1.00000000e-01, -1.38777878e-17],
        [ 4.25000000e-01, -1.25000000e-01]])

- 넘파이 모듈의 함수의 특징
    - 동일한 이름의 함수와 메소드 지원

In [64]:
# 함수와 메소드 처리
a =np.zeros((5,5), dtype=int)

In [65]:
print(a.shape)
print()
print(a)
print()
print(a != 0)

(5, 5)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


In [66]:
print((a != 0).any())
print()
print(np.any(a!=0))

False

False


In [67]:
print((a != 0).any)
print()
print(np.any)
print()
print(np.ndarray.any is np.core.fromnumeric.any)

<built-in method any of numpy.ndarray object at 0x0000021C87B5A730>

<function any at 0x0000021C879BCF40>

False


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_23836\3605564358.py:5: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.
  print(np.ndarray.any is np.core.fromnumeric.any)


In [68]:
help(np.ndarray.any)

Help on method_descriptor:

any(...) unbound numpy.ndarray method
    a.any(axis=None, out=None, keepdims=False, *, where=True)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [69]:
help(a.any)

Help on built-in function any:

any(...) method of numpy.ndarray instance
    a.any(axis=None, out=None, keepdims=False, *, where=True)
    
    Returns True if any of the elements of `a` evaluate to True.
    
    Refer to `numpy.any` for full documentation.
    
    See Also
    --------
    numpy.any : equivalent function



In [70]:
np_ = set(dir(np))
nd_ = set(dir(np.ndarray))
npd_ = np_ & nd_
print(len(npd_))

48


In [71]:
print(len(nd_))

169


In [72]:
print(len(np_))

530


In [73]:
count = 0
for i in list(npd_):
    count += 1
    print(i, end=" ")
    if count % 5 == 0:
        print()

conj diagonal shape choose max 
ptp reshape swapaxes ravel round 
nonzero astype take sum cumprod 
argmin min argsort any cumsum 
prod transpose argmax resize compress 
__doc__ repeat argpartition sort put 
mean dot squeeze var imag 
all size std dtype real 
searchsorted __dir__ conjugate clip trace 
ndim partition copy 

- 넘파이 모듈의 함수의 특징
    - 유니버셜 함수 제공

In [74]:
a = dir(np)
print(np.ufunc)

<class 'numpy.ufunc'>


In [75]:
# 왜 char 오류가 났는지 모르겠음
count = 0
# for i in a:
#     if i == 'Tester':
#         continue
#     if type(np.__dict__[i]) == np.ufunc:
#         print(i, end=" ")
#         count += 1
#         if count % 5 == 0:
#             print()

In [76]:
import types

In [77]:
count = 0
# for i in a:
#     if i == "Tester":
#         continue
#     if type(np.__dict__[i]) == types.FunctionType:
#         count += 1
# print(count)

In [78]:
print(type(np.add))
print(type(np.sort))

<class 'numpy.ufunc'>
<class 'numpy._ArrayFunctionDispatcher'>


In [79]:
set(dir(np.add)) - set(dir(np.sort))

{'_get_strided_loop',
 '_resolve_dtypes_and_context',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'resolve_dtypes',
 'signature',
 'types'}

In [80]:
a = np.array([1, 2, 3, 4])
print(np.add(a, a))
print(np.add.accumulate(a))

[2 4 6 8]
[ 1  3  6 10]


- 넘파이 모듈의 함수 특징
    - 벡터화 연산 이해하기

In [81]:
a = np.arange(6, 10)
a

array([6, 7, 8, 9])

In [82]:
b = np.arange(10, 14)
b

array([10, 11, 12, 13])

In [83]:
c = a + b
c

array([16, 18, 20, 22])

In [84]:
d = a[:, np.newaxis]
d

array([[6],
       [7],
       [8],
       [9]])

In [85]:
d.shape

(4, 1)

In [86]:
e = b[np.newaxis, :]
e

array([[10, 11, 12, 13]])

In [87]:
e.shape

(1, 4)

In [88]:
f = d @ e
f

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [89]:
d.dot(e)

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

- 넘파이 모듈의 함수의 특징
    - 축(axis) 계산이 필요한 경우

In [90]:
# 축에 따른 연산
a2 = np.array([1, 2, 3, 4])
a2

array([1, 2, 3, 4])

In [91]:
a2 = a2.reshape(2, 2)
a2

array([[1, 2],
       [3, 4]])

In [92]:
print(np.sum(a2))
print(np.sum(a2, axis=0))
print(np.sum(a2, axis=1))

10
[4 6]
[3 7]


In [93]:
a3 = np.arange(1, 9)
a3

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
a3 = a3.reshape(2, 2, 2)
a3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [95]:
print(a3.shape)
print(a3[0])
print(a3[1])

(2, 2, 2)
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [96]:
print(np.sum(a3))
print(np.sum(a3, axis=0))
print(np.sum(a3, axis=1))
print(np.sum(a3, axis=2))

36
[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


- 넘파이 모듈의 함수 특징
    - 계산할 때 원소의 개수 일치하기

In [97]:
# 원소별 연산하기
a = np.array([4, 5])
print(a.shape)
b = np.array([3, 4, 6])
print(b.shape)

(2,)
(3,)


In [98]:
try:
    a + b
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,) (3,) 


In [99]:
a = np.append(a, [6])
print(a.shape)
a + b

(3,)


array([ 7,  9, 12])

In [100]:
a2 = np.array([[1, 2, 3], [3, 4, 5]])
b2 = np.array([1, 2])

try:
    a2 + b2
except Exception as e:
    print(e)

operands could not be broadcast together with shapes (2,3) (2,) 


In [101]:
b2 = np.append(b2, [3])
print(b2.shape)
a2 + b2

(3,)


array([[2, 4, 6],
       [4, 6, 8]])

- 배열의 할당과 검색
    - 복사(copy)와 뷰(view) 이해하기

In [102]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [103]:
b = a
b

array([[1, 2],
       [3, 4]])

In [104]:
print(a is b)
print(a is b.base)

True
False


In [105]:
b[0] = 999
print(a)
print(b)

[[999 999]
 [  3   4]]
[[999 999]
 [  3   4]]


In [106]:
# 다차원 배열의 원본을 메모리에 공유하기
f = np.array([4, 5, 6, 7, 8])
e = f.copy()
e.base is None

True

In [107]:
g = f[:]
print(g.base)
print(g.base is f)

[4 5 6 7 8]
True


In [108]:
np.may_share_memory(g, f)

True

In [109]:
g[1] = 9999
print(g)
print(f)

[   4 9999    6    7    8]
[   4 9999    6    7    8]


In [110]:
h = f.view()
print(h)
print(h.base is f)
print(np.may_share_memory(h, f))

[   4 9999    6    7    8]
True
True


In [111]:
a = np.array([1, 3, 5, 7])
b = np.array(a, copy=True)
print(b.base is None)
c = np.array(a)
print(c.base is None)

True
True


- 배열의 할당과 검색
    - 새로운 배열의 생성 여부 확인

In [112]:
# 배열 생성과 변경
aa = np.array([1, 2, 3, 4, 5, 6, 7])
aa_c = np.sort(aa, axis=0)
print(aa_c)
print(aa_c.base is None)

[1 2 3 4 5 6 7]
True


In [113]:
aa[6] = 0
aa.sort()
aa

array([0, 1, 2, 3, 4, 5, 6])

- 배열의 할당과 검색
    - 검색과 슬라이싱

In [114]:
# 검색과 슬라이싱
l = list(range(1, 10))
print(l)
index = 1
print(l.__getitem__(index))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
2


In [115]:
index = slice(1, 3)
l.__getitem__(index)

[2, 3]

In [116]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
index = 1
a.__getitem__(index)

np.int64(2)

In [117]:
index = slice(1, 3)
a.__getitem__(index)

array([2, 3])

In [118]:
index = 1
print(a.__getitem__(index))
index = [1]
print(a.__getitem__(index))

2
[2]


In [119]:
index = a < 4
print(index)
print(a.__getitem__(index))

[ True  True  True False False False False]
[1 2 3]


In [120]:
index = a < 3
a.__setitem__(index, 9080)
a

array([9080, 9080,    3,    4,    5,    6,    7])