### 넘파이 Chapter 2
- 스칼라와 벡터 알아보기
- 행렬(Matrix) 알아보기
- 행렬(Matrix) 종류 알아보기

In [1]:
import numpy as np

- 스칼라와 벡터 알아보기
    - 스칼라(scalar) 이해하기

In [2]:
# 스칼라 알아보기
a = np.array(43)
print(type(a))
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a == 43)

<class 'numpy.ndarray'>
43
0
()
int64
True


In [3]:
i = int(43)
try:
    i.ndim
except Exception as e:
    print(e)

'int' object has no attribute 'ndim'


- 스칼라와 벡터 알아보기
    - 벡터(Vector) 이해하기

In [4]:
# 벡터 알아보기
v = np.array([43])
print(type(v))
print(v)

<class 'numpy.ndarray'>
[43]


In [5]:
print(v.ndim)
print(v.shape)

1
(1,)


- 스칼라와 벡터 이해하기
    - 1차원 배열 전용 생성 함수

In [7]:
# arange 함수로 벡터 생성하기
v = np.arange(10)
print(v)
print(v.dtype)
print()
v1 = np.arange(10.5, 20.5, 0.5)
print(v1)
print(v1.dtype)
print(v1.size)

[0 1 2 3 4 5 6 7 8 9]
int64

[10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5 17.
 17.5 18.  18.5 19.  19.5 20. ]
float64
20


In [8]:
v3 = np.arange(60).reshape(6, 10)
print(v3.shape)
print()
v4 = np.arange(60).reshape(3, 4, 5)
print(v4.shape)

(6, 10)

(3, 4, 5)


In [9]:
# linspace 함수로 벡터 생성하기
la = np.linspace(1, 10, 10)
print(la)
print(la.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [10]:
la2 = np.linspace(1, 2, 10, retstep=True)
print(la2)
print(la2[0].size)

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]), np.float64(0.1111111111111111))
10


In [11]:
la1 = np.linspace(1, 10, 10, endpoint=False, retstep=True)
print(la1)

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), np.float64(0.9))


In [12]:
lo = m=np.logspace(0, 2, 4)
print(lo)
print()

la2 = np.linspace(0, 2, 4)
print(la2)

[  1.           4.64158883  21.5443469  100.        ]

[0.         0.66666667 1.33333333 2.        ]


In [13]:
for i in la2:
    print(np.power(10, i))

1.0
4.641588833612778
21.544346900318832
100.0


- 스칼라와 벡터 알아보기
    - 벡터 크기 및 단위 벡터 구하기

In [14]:
# 벡터 크기 계산하기
v = np.arange(3, 5)
v

array([3, 4])

In [15]:
v_p = np.power(v, 2)
v_r = np.sqrt(np.sum(v_p))
v_r

np.float64(5.0)

In [16]:
np.hypot(v[0], v[1])

np.float64(5.0)

In [18]:
np.linalg.norm(v)   # 벡터의 크기? 고유값?

np.float64(5.0)

In [19]:
# 단위벡터 계산하기
e1 = np.array([1, 0, 0])
print(np.linalg.norm(e1))
print()

e2 = np.array([0, 1, 0])
print(np.linalg.norm(e2))
print()

e3 = np.array([0, 0, 1])
print(np.linalg.norm(e3))

1.0

1.0

1.0


In [20]:
# 벡터의 표준화
v_3 = np.array([1, 2, 3])
v_3_n = np.linalg.norm(v_3)
v_3_n

np.float64(3.7416573867739413)

In [23]:
v_3_u = v_3 / v_3_n
print(v_3_u)
print(np.linalg.norm(v_3_u))

[0.26726124 0.53452248 0.80178373]
1.0


In [24]:
# 단위 벡터를 구하는 함수?
def normal(v):
    return v / np.sqrt(np.dot(v, v))

In [25]:
v_4 = np.array([1, 2, 3, 4])
v_4_u = normal(v_4)
print(v_4_u)
print(np.linalg.norm(v_4_u))
print(np.round(np.linalg.norm(v_4_u), 10))

[0.18257419 0.36514837 0.54772256 0.73029674]
0.9999999999999999
1.0


- 스칼라와 벡터 알아보기
    - 두 벡터 상등과 두 벡터간 거리 구하기

In [26]:
# 두 벡터가 동일하다
a = np.arange(3, 5)
b = np.arange(3, 5)
np.array_equal(a, b)

True

In [27]:
a_1 = np.linalg.norm(a)
b_1 = np.linalg.norm(b)
a_1 == b_1

np.True_

In [28]:
b_2 = -1 * np.linalg.norm(b)
a_1 == b_2

np.False_

In [29]:
# 두 벡터의 거리 구하기
c = np.arange(10, 13)
d = np.arange(0, 3)
print(np.sqrt(np.sum(np.square(c-d))))
print(np.linalg.norm(c-d))

17.320508075688775
17.320508075688775


- 행렬 알아보기
    - 행렬(Matrix) 이해하기

In [30]:
# 행렬 알아보기
A = np.array([[43], [44]])
print(type(A))
print(A)

<class 'numpy.ndarray'>
[[43]
 [44]]


In [31]:
print(A.dtype)
print(A.ndim)
print(A.shape)

int64
2
(2, 1)


In [35]:
shape = (3, 4)
dtype = np.int64
B = np.full(shape, 7, dtype)
print(B)
print(B.dtype)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
int64


- 행렬 알아보기
    - 행렬의 랭크 이해하기

In [37]:
# 랭크 알아보기
v1 = np.array([1, 2, 3, 4])
np.linalg.matrix_rank(v1)

1

In [49]:
c = np.array([[1, 2, 4], [2, 4, 8]])
print(c)
print(np.linalg.matrix_rank(c))

[[1 2 4]
 [2 4 8]]
1


In [50]:
c1 = np.array([[1, 2, 4], [2, 4, 8], [3, 4, 5]])
np.linalg.matrix_rank(c1)

np.int64(2)

In [52]:
print(np.linalg.det(c1))    # 선형독립 여부
print(c1[0] * 2 - c1[1])    # 선형종속 여부

0.0
[0 0 0]


In [53]:
c2 = np.array([[1, 3, 4], [1, 8, 5], [2, 3, 4]])
np.linalg.matrix_rank(c2)

np.int64(3)

In [54]:
print(np.linalg.det(c2))
print(np.linalg.matrix_rank(c2.T))

-17.0
3


In [55]:
c3 = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])
print(c3)
print(np.linalg.matrix_rank(c3))
print(np.linalg.det(c3))

[[1 2 3]
 [4 5 6]
 [0 0 0]]
2
0.0


- 행렬 알아보기
    - 축(Axis) 이해하기

In [57]:
# 배열 축 알아보기
a = np.arange(1, 10)
print(a.sum())
print(np.sum(a))

45
45


In [58]:
print(a.sum(axis=0))
print(np.sum(a, axis=0))

45
45


In [60]:
A = np.array([[2, 3], [4, 5]])
print(A.sum())
print(A.sum(axis=0))
print(A.sum(axis=1))

14
[6 8]
[5 9]


In [61]:
C = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]])
print(C.ndim)
print(C.shape)
print()

print(C[0])
print(C[1])
print()

print(C.sum(axis=0))
print(C.sum(axis=1))
print(C.sum(axis=2))

3
(2, 2, 2)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

[[ 6  8]
 [10 12]]
[[ 4  6]
 [12 14]]
[[ 3  7]
 [11 15]]


In [62]:
# 배열의 툭 변환 알아보기
t = np.arange(3*4*2)
print(t)
print()

t1 = np.reshape(t, (3, 4, 2))
print(t1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]

 [[16 17]
  [18 19]
  [20 21]
  [22 23]]]


In [63]:
print(t1.shape)
print()

t2 = t1.transpose(0, 2, 1)
print(t2.shape)
print()

print(t2)

(3, 4, 2)

(3, 2, 4)

[[[ 0  2  4  6]
  [ 1  3  5  7]]

 [[ 8 10 12 14]
  [ 9 11 13 15]]

 [[16 18 20 22]
  [17 19 21 23]]]


In [64]:
ra = np.ones((3, 4, 5, 3))
print(ra.shape)
print(ra.shape[3])
print(np.rollaxis(ra, 3, 1).shape)

(3, 4, 5, 3)
3
(3, 3, 4, 5)


In [66]:
x = np.array([[1, 2, 3]])
print(x.T)
print()
print(np.swapaxes(x, 0, 1))

[[1]
 [2]
 [3]]

[[1]
 [2]
 [3]]


In [67]:
print(ra.shape)

ra21 = np.swapaxes(ra, 2, 1)
print(ra21.shape)

(3, 4, 5, 3)
(3, 5, 4, 3)


- 행렬 알아보기
    - 배열 확장 및 축소하기

In [68]:
# 배열 확장 및 축소하기
x = np.array([1, 2])
x

array([1, 2])

In [69]:
y = np.expand_dims(x, axis=1)
y

array([[1],
       [2]])

In [70]:
z = np.expand_dims(x, axis=0)
z

array([[1, 2]])

In [71]:
# 차원 배열로 데이터 보기
x = np.array([[1, 4, 5], [4, 5, 6], [7, 8, 9]])
print(x)
print()

print(x.flatten())
print(x.ravel())
print()

print(np.may_share_memory(x.flatten(), x))
print(np.may_share_memory(x.ravel(), x))

[[1 4 5]
 [4 5 6]
 [7 8 9]]

[1 4 5 4 5 6 7 8 9]
[1 4 5 4 5 6 7 8 9]

False
True


- 행렬종류 알아보기
    - 정사각행렬 이해하기: Square Matrix

In [73]:
# 행렬의 궤적 알아보기
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])
print(a)
print()
print(a.shape)
print(np.trace(a))
print(a.trace())

[[1 2 3]
 [4 5 6]
 [7 8 8]]

(3, 3)
14
14


In [74]:
# 대각행렬 알아보기: Diagonal Matrirx
b = np.array([[1, 0, 0], [0, 3, 0], [0, 0, 5]])
print(b)
print()

print(b.diagonal())
print(np.diagonal(b))

[[1 0 0]
 [0 3 0]
 [0 0 5]]

[1 3 5]
[1 3 5]


In [76]:
# 대각행렬 만들기
c = np.diag(np.arange(1, 4))
print(c)
print()

d = np.diag(np.arange(1, 4), k=1)
print(d)
print()

e = np.diag(np.arange(1, 4), k=-1)
print(e)
print()

f = np.diag([[1, 2], [3, 4]])
print(f)
print()

g = np.diagonal([[1, 2], [3, 4]])
print(g)

[[1 0 0]
 [0 2 0]
 [0 0 3]]

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]

[[0 0 0 0]
 [1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]

[1 4]

[1 4]


In [77]:
# 단위행렬 만들기: Unit Matrix
h = np.eye(3, 3)
print(h)
print()

i = np.eye(3, 3, k=1)
print(i)
print()

j = np.eye(3, 3, k=-1)
print(j)
print()

k = np.diag([4, 4, 4])
print(k)
print()

k * 1 /4

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]

[[4 0 0]
 [0 4 0]
 [0 0 4]]



array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [78]:
# 항등행렬 만들기
l = np.identity(3)
print(l)
print()

s = np.arange(1, 10).reshape(3, 3)
print(s)
print(s.dot(l))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


- 행렬종류 알아보기
    - 삼각행렬 이해하기

In [79]:
# 하삼각행렬 알아보기: Lower Trianglular Matrix
a = np.arange(1, 10).reshape(3, 3)
print(a)
print()

print(np.tril(a))
print(np.tril(a, k=-1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 0 0]
 [4 5 0]
 [7 8 9]]
[[0 0 0]
 [4 0 0]
 [7 8 0]]


In [80]:
# 상삼각행렬 알아보기: Upper Triangular Matrix
b = np.arange(1, 10).reshape(3, 3)
print(b)
print()

print(np.triu(b))
print()

print(np.triu(b, k=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [0 5 6]
 [0 0 9]]

[[0 2 3]
 [0 0 6]
 [0 0 0]]


In [81]:
# 삼각행렬 전치관계 알아보기
c = np.triu(b)
print(c)
print()

print(c.T)
print()

d = np.tril(b)
print(d.T)
print()

print(d*d)
print()

print(c*c)
print()

print(d*c)

[[1 2 3]
 [0 5 6]
 [0 0 9]]

[[1 0 0]
 [2 5 0]
 [3 6 9]]

[[1 4 7]
 [0 5 8]
 [0 0 9]]

[[ 1  0  0]
 [16 25  0]
 [49 64 81]]

[[ 1  4  9]
 [ 0 25 36]
 [ 0  0 81]]

[[ 1  0  0]
 [ 0 25  0]
 [ 0  0 81]]


- 행렬종류 이해하기
    - 영행렬 이해하기: Null Matrix, Zero Matrix

In [82]:
# 영행렬 만들기
z = np.zeros((3, 3))
print(z)
print()

z0 = np.zeros(3)
print(z0)
print()

z1 = np.zeros_like(np.arange(1, 10).reshape(3, 3))
print(z1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[0. 0. 0.]

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [83]:
# 임의의 행렬 만들기
e = np.empty(3)
print(e)
print()

e33 = np.empty((3, 3))
print(e33)

[0. 0. 0.]

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


- 행렬종류 알아보기
    - 대칭행렬 이해하기: Symmetric Matrix

In [84]:
# 대칭행렬 확인하기
X = np.array([[1, 2, 3], [2, 3, 5], [3, 5, 6]])
print(X)
print()

print(X.T)
print()

print(np.array_equal(X, X.T))
print(np.array_equiv(X, X.T))

[[1 2 3]
 [2 3 5]
 [3 5 6]]

[[1 2 3]
 [2 3 5]
 [3 5 6]]

True
True


In [86]:
print(X + X.T)
print()

print(np.dot(X, X.T))
print()

a = np.transpose(np.dot(X, X.T))
b = np.dot(X.T, X)
print(a == b)

[[ 2  4  6]
 [ 4  6 10]
 [ 6 10 12]]

[[14 23 31]
 [23 38 51]
 [31 51 70]]

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [87]:
# 반 대칭행렬(Skew Symmetric Matrix) 확인하기
Y = np.array([[0, 2, -3], [-2, 0, 5], [3, -5, 0]])
print(Y)
print()

print(Y + Y.T)
print()

print(Y.T == Y)
print()

print(Y - Y.T)
print()

print(np.dot(Y, Y.T))
print()

print(np.dot(Y.T, Y))

[[ 0  2 -3]
 [-2  0  5]
 [ 3 -5  0]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[ True False False]
 [False  True False]
 [False False  True]]

[[  0   4  -6]
 [ -4   0  10]
 [  6 -10   0]]

[[ 13 -15 -10]
 [-15  29  -6]
 [-10  -6  34]]

[[ 13 -15 -10]
 [-15  29  -6]
 [-10  -6  34]]


- 행렬종류 알아보기
    - 치환행렬(Permutation Matrix)

In [88]:
# 행 바꿈 알아보기
a = np.arange(1, 10).reshape(3, 3)
print(a)
print()

b = np.eye(3, dtype='int')
print(b)
print()

print(np.dot(a, b))
print()

c = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
print(np.dot(a, c))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 1 3]
 [5 4 6]
 [8 7 9]]


- 행렬종류 알아보기
    - 직교행렬(Orthogonal Matrix)

In [89]:
# 직교행렬 알아보기
from scipy.stats import ortho_group

In [90]:
X = ortho_group.rvs(3)
print(X)
print()

i3 = np.dot(X, X.T)
print(i3)

[[ 0.78806096 -0.40664297 -0.46217034]
 [-0.61117229 -0.42696981 -0.66645721]
 [-0.07367735 -0.80767461  0.58500716]]

[[ 1.00000000e+00  2.38847623e-17 -4.55084314e-17]
 [ 2.38847623e-17  1.00000000e+00 -2.33641910e-16]
 [-4.55084314e-17 -2.33641910e-16  1.00000000e+00]]


In [91]:
C = np.eye(3)
print(np.allclose(C, i3))
print(np.fabs(np.linalg.det(X)))

True
0.9999999999999996


- 행렬종류 알아보기
    - 전치행렬(Transpose Matrix)

In [92]:
# 전치행렬 알아보기
a = np.array([[1, 2], [3, 4]])
print(a)
print()

print(a.T)
print()

print(a.transpose())
print()

print(np.transpose(a))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]

[[1 3]
 [2 4]]
