### 넘파이 Chapter 3
- 배열의 일반 검색
- 논리식 검색(logical indexing)
- 팬시 검색(fancy indexing)
- 메소드나 함수로 검색하기

In [1]:
import numpy as np

- 배열의 일반 검색
    - 색인검색(Scalar Selection)

In [2]:
# 색인검색
v = np.array([1, 2, 3, 4, 5])
print(v[0])
print(v[-1])

1
5


In [3]:
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(A[0])
print(A[-1])
print()

print(A[0, 1])
print(A[-1, -1])
print()

print(A[(1, 3)])
print(A.__getitem__((1, 3)))

[1 2 3 4 5]
[ 6  7  8  9 10]

2
10

9
9


- 배열의 일반 검색
    - 슬라이스검색(Slice Selection)

In [4]:
# 슬라이스검색
B = np.arange(9).reshape(3, 3)
print(B)
print()

print(B.shape)
print(B[0,:])
print(B[0])
print(B[:, 0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]

(3, 3)
[0 1 2]
[0 1 2]
[0 3 6]


In [5]:
print(B[:2, 1:])
print(B[::2, ::2])
print(B.flat)
print(B.flat[:])
print(B.flat[::2])

[[1 2]
 [4 5]]
[[0 2]
 [6 8]]
[0 1 2 3 4 5 6 7 8]
[0 2 4 6 8]


- 배열의 일반 검색
    - 생략기호를 사용한 접근

In [6]:
# 생략기호를 사용해서 검색하기
A = np.arange(1, 60, 5).reshape(3, 4)
print(A)
print()

print(...)  # 생략기호
print(type(...))
print()

print(A[...])
print()

print(A[:2, ...])
print()

print(A[..., :2])

[[ 1  6 11 16]
 [21 26 31 36]
 [41 46 51 56]]

Ellipsis
<class 'ellipsis'>

[[ 1  6 11 16]
 [21 26 31 36]
 [41 46 51 56]]

[[ 1  6 11 16]
 [21 26 31 36]]

[[ 1  6]
 [21 26]
 [41 46]]


In [7]:
B = np.arange(16).reshape(2, 2, 2, 2)
print(B)
print()

print(B[..., 0])
print()

print(B[..., 0].flatten())
print()

print(B[:, :, :, 0])
print()

print(B[:, :, :, 0].flatten())

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]

[ 0  2  4  6  8 10 12 14]

[[[ 0  2]
  [ 4  6]]

 [[ 8 10]
  [12 14]]]

[ 0  2  4  6  8 10 12 14]


- 논리식 검색
    - 논리식 접근

In [8]:
# 논리식으로 접근하기
L = np.random.randn(7, 4)
print(L)
print()

print(L < 0)
print()

print(L[L < 0])
print()

L[L < 0] = 999
print(L)
print()

LC = L[L == 999]
print(LC)
print()

LC[0] = 1000
print(LC)
print()

print(L == 1000)
print()

LL = L
print(np.may_share_memory(LC, L))
print(np.may_share_memory(LL, L))

[[ 0.4834878  -1.11399548 -0.42085448 -0.6684847 ]
 [-0.96963528 -0.09834069  1.71426358 -0.79843642]
 [-0.57549069 -0.84239972  0.06796588  1.10389359]
 [ 0.99191325 -0.18089914  1.13537406 -1.73125573]
 [ 0.94556586  0.52745701  0.0678981   0.48139326]
 [ 2.01153153  1.77141638 -0.98600729  1.5726753 ]
 [-0.21710032 -0.64317422 -0.27806295 -1.64803585]]

[[False  True  True  True]
 [ True  True False  True]
 [ True  True False False]
 [False  True False  True]
 [False False False False]
 [False False  True False]
 [ True  True  True  True]]

[-1.11399548 -0.42085448 -0.6684847  -0.96963528 -0.09834069 -0.79843642
 -0.57549069 -0.84239972 -0.18089914 -1.73125573 -0.98600729 -0.21710032
 -0.64317422 -0.27806295 -1.64803585]

[[4.83487803e-01 9.99000000e+02 9.99000000e+02 9.99000000e+02]
 [9.99000000e+02 9.99000000e+02 1.71426358e+00 9.99000000e+02]
 [9.99000000e+02 9.99000000e+02 6.79658833e-02 1.10389359e+00]
 [9.91913254e-01 9.99000000e+02 1.13537406e+00 9.99000000e+02]
 [9.45565865e

- 논리식 검색
    - 다양한 논리식 검색

In [9]:
# 다양한 논리식 적용하기
L = np.arange(0, 12).reshape(3, 4)
print(L)
print()

print(L[L < 5])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[0 1 2 3 4]


In [10]:
print(L % 3)
print()

print(L[L%3 > 0])
print()

print(L.nonzero())
print(L[L.nonzero()])

[[0 1 2 0]
 [1 2 0 1]
 [2 0 1 2]]

[ 1  2  4  5  7  8 10 11]

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[ 1  2  3  4  5  6  7  8  9 10 11]


- 논리식 검색
    - 논리식 접근 시 주의 사항


In [11]:
# 논리연산 사용상 주의
L = np.arange(0, 12)
print(L)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [12]:
try:
    L and L
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


In [13]:
print(np.logical_and(L, L))
print(L[np.logical_and(L, L)])

[False  True  True  True  True  True  True  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10 11]


In [14]:
print(np.logical_or(L, L))
print(L[np.logical_or(L, L)])
print(np.logical_not(L))
print(L[np.logical_not(L)])

[False  True  True  True  True  True  True  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10 11]
[ True False False False False False False False False False False False]
[0]


In [17]:
LL = np.arange(0, 12).astype(np.bool)
print(LL)
print(LL & LL)
print(LL | LL)
print(~ LL)

[False  True  True  True  True  True  True  True  True  True  True  True]
[False  True  True  True  True  True  True  True  True  True  True  True]
[False  True  True  True  True  True  True  True  True  True  True  True]
[ True False False False False False False False False False False False]


- 팬시검색
    - 1차원 배열로 원소만 추출

In [18]:
# 배열로 원소 검색하기
x = np.arange(1, 15)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
pos = np.array([10])
print(pos)
print(x[0])
print(x[pos])

[10]
1
[11]


In [21]:
pos2 = np.array([1, 2, 2, 2])
print(x[pos2])
print()

c = x[pos2]
print(np.may_share_memory(x, c))
print()

y = x[:4]
print(np.may_share_memory(x, y))


[2 3 3 3]

False

True


In [22]:
print(len(x))

try:
    x[[15]]
except Exception as e:
    print(e)

14
index 15 is out of bounds for axis 0 with size 14


In [23]:
d = x[[-5, -4, -3, -2, -1]]
print(d)
print()

d[0] = 100
print(x[-5])

[10 11 12 13 14]

10


In [24]:
d[0]

np.int64(100)

In [25]:
d[1]

np.int64(11)

In [26]:
d[-5]

np.int64(100)

In [27]:
# 2차원 배열의 우너소를 검색하기
x = np.arange(16).reshape(4, 4)
print(x)
print()

print(x[[3, 0]])
print()

print(x[[-1, -2]])
print()

print(x[[1, 2], [2, 3]])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[12 13 14 15]
 [ 0  1  2  3]]

[[12 13 14 15]
 [ 8  9 10 11]]

[ 6 11]


In [28]:
# ix_를 사용해서 검색하기
a = np.array([[2, 3, 4, 5], [8, 9, 0, 1]])
print(a)
print()

print(a[[0, 1], [0, 1]])
print()

print(a[tuple([[0, 1], [0, 1]])])
print()

print(type(np.ix_))
print(a[np.ix_([0, 1], [0, 1])])

[[2 3 4 5]
 [8 9 0 1]]

[2 9]

[2 9]

<class 'numpy._ArrayFunctionDispatcher'>
[[2 3]
 [8 9]]


- 팬시검색
    - 다차원 배열로 팬시검색하기

In [29]:
# 다차원 배열로 조회하기
x = np.arange(10).reshape(2, 5)
print(x)
print()

print(x[tuple([[0, 1], [0, 1]])])
print()

print(x[[[0, 1], [0, 1]], [0, 1]])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 6]

[[0 6]
 [0 6]]


- 팬시검색
    - 다른 검색과 팬시검색 혼용하기

In [30]:
# 인덱스 검색과 혼용하기
x = np.arange(10).reshape(2, 5)
print(x)
print()

print(x[0, [0,1]])
print()

print(x[1, [0, 1]])
print()

print(1, tuple([0, 1]))
print()

print(x[[0, 1]])
print()

print(x[[0, 1], 0])
print()

a = x[[0, 1], 0]
print(np.may_share_memory(x, a))

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1]

[5 6]

1 (0, 1)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 5]

False


In [31]:
# 슬라이스검색과 혼용하기
y = np.arange(10).reshape(2, 5)
print(y)
print()

print(y[[0, 1], :2])
print()

print(y[:2, [0, 1]])
print()

print(y[[0, 1], -2:])
print()

print(y[-2:, [0, 1]])

[[0 1 2 3 4]
 [5 6 7 8 9]]

[[0 1]
 [5 6]]

[[0 1]
 [5 6]]

[[3 4]
 [8 9]]

[[0 1]
 [5 6]]


In [33]:
# 다양한 검색조건 확인하기
a = np.arange(6)
print(a)
print()

b = np.arange(0, 51, 10)[:, np.newaxis]
print(b)
print()

c = a + b
print(c)
print()

print(c[tuple([[1, 3, 4], [3, 4, 5]])])
print()

print(c[:, [0, 2, 5]])

[0 1 2 3 4 5]

[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]

[13 34 45]

[[ 0  2  5]
 [10 12 15]
 [20 22 25]
 [30 32 35]
 [40 42 45]
 [50 52 55]]


In [34]:
mask = np.array([1, 0, 1, 0, 0, 1], dtype=bool)
print(mask)
print()

d = c[mask]
print(d)
print()

print(np.may_share_memory(c, d))
print()

print(c[mask])
print()

try:
    c[mask, tuple([0, 1])]
except Exception as e:
    print(e)
    
print(c[mask][[0, 1]])

[ True False  True False False  True]

[[ 0  1  2  3  4  5]
 [20 21 22 23 24 25]
 [50 51 52 53 54 55]]

False

[[ 0  1  2  3  4  5]
 [20 21 22 23 24 25]
 [50 51 52 53 54 55]]

shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 
[[ 0  1  2  3  4  5]
 [20 21 22 23 24 25]]


- 팬시검색
    - 배열을 축소 및 확대하기

In [35]:
# 차원의 축소
x = np.arange(9).reshape(3, 3)
print(x)
print()

a = x[1:, 1:]
print(a)
print()

print(np.may_share_memory(x, a))
print()

b = x[1:, [1, 2]]
print(b)
print()

print(np.may_share_memory(x,b))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[4 5]
 [7 8]]

True

[[4 5]
 [7 8]]

False


In [37]:
# 확대 검색하기
a = np.reshape(np.arange(10), (2, 5))
print(a)
print()

b = a[[1, 1, 1]]
print(b.shape)
print(b)

[[0 1 2 3 4]
 [5 6 7 8 9]]

(3, 5)
[[5 6 7 8 9]
 [5 6 7 8 9]
 [5 6 7 8 9]]


In [38]:
c = a[[1, 1, 1], np.newaxis]
print(c.shape)
print(c)
print()

d = a[np.newaxis, [1, 1, 1]]
print(d.shape)
print(d)
print()

(3, 1, 5)
[[[5 6 7 8 9]]

 [[5 6 7 8 9]]

 [[5 6 7 8 9]]]

(1, 3, 5)
[[[5 6 7 8 9]
  [5 6 7 8 9]
  [5 6 7 8 9]]]



In [39]:
print(tuple([[1, 1], [0, 1]]))
print(tuple([[1, 1], [0, 1]]))
print(tuple([[[1, 1], [0, 1]]]))
print()

print(a[tuple([[[1, 1], [0, 1]]])])

([1, 1], [0, 1])
([1, 1], [0, 1])
([[1, 1], [0, 1]],)

[[[5 6 7 8 9]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]]


In [41]:
e = a[[[1, 1], [0, 1]], :]
print(e.shape)
print(e)

(2, 2, 5)
[[[5 6 7 8 9]
  [5 6 7 8 9]]

 [[0 1 2 3 4]
  [5 6 7 8 9]]]


In [42]:
f = a[[[1, 1], [0, 1]], :1]
print(f.shape)
print(f)
print()

g = a[[[1, 1], [0, 1]], [0]]
print(g.shape)
print(g)

(2, 2, 1)
[[[5]
  [5]]

 [[0]
  [5]]]

(2, 2)
[[5 5]
 [0 5]]


- 메소드나 함수로 검색하기
    - 메소드 사용하기

In [43]:
# 배열의 원소 검색
x = np.arange(9).reshape(3, 3)
print(x)
print()

print(x.item(1))
print(x.item(5))
print(x.item(1, 2))
print(x.item((2, 2)))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

1
5
5
8


In [47]:
x[2] = 20
print(x)
print()

x[1 ,2] = 20
print(x)
print()

print(x.view)

[[ 0  1 20]
 [ 3  4 20]
 [20 20 20]]

[[ 0  1 20]
 [ 3  4 20]
 [20 20 20]]

<built-in method view of numpy.ndarray object at 0x0000026523A3A6D0>


In [48]:
# 배열의 원소를 배열조건으로 검색
b = np.linspace(1, 10, 10).reshape(2, 5)
print(b)
print()

pos1 = [3, 4]
print(b.take(pos1))
pos2 = [[0, 1], [3, 4]]
print(b.take(pos2))

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]

[4. 5.]
[[1. 2.]
 [4. 5.]]


In [49]:
c = b.copy()
print(np.may_share_memory(c, b))
print()

print(c.put(pos1, 30))
print(c)
print()

print(c.put(pos1, [50,50]))
print(c)

False

None
[[ 1.  2.  3. 30. 30.]
 [ 6.  7.  8.  9. 10.]]

None
[[ 1.  2.  3. 50. 50.]
 [ 6.  7.  8.  9. 10.]]


- 메소드나 함수로 검색하기
    - 질의(Query) 함수를 사용하기

In [50]:
# 질의 함수 사용하기
x = np.arange(9).reshape(3, 3)
print(x)
print()

print(np.choose(0, x))
print(np.choose([0], x))
print(np.choose(1, x))
print(np.choose(2, x))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[0 1 2]
[0 1 2]
[3 4 5]
[6 7 8]


In [51]:
try:
    np.choose(3, x)
except Exception as e:
    print(e)

invalid entry in choice array


In [52]:
print(tuple([0, 1, 2]))
print(np.choose(tuple([0, 1, 2]), x))
print(np.choose(tuple([2, 1, 0]), x))
print()

print(tuple([[0], [1], [2]]))
print(np.choose(tuple([[0], [1], [2]]), x))
print()
print(np.choose(tuple([[0], [1], [2], [2]]), x))

(0, 1, 2)
[0 4 8]
[6 4 2]

([0], [1], [2])
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [6 7 8]]


In [53]:
print(np.where(x > 4))
print(x[np.where(x > 4)])
print(x)
print()
print(x > 5)
print(np.select(x > 5, x))


(array([1, 2, 2, 2]), array([2, 0, 1, 2]))
[5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[False False False]
 [False False False]
 [ True  True  True]]
[6 7 8]


In [54]:
a = np.select(x>5, x)
a

array([6, 7, 8])

In [55]:
np.extract(x>4, x)

array([5, 6, 7, 8])