### 넘파이 Chapter 4
- 산술연산
- 브로드캐스팅 이해하기
- 행렬의 연산
- 행렬식(determineant), 역행렬(Inverse Matrix) 처리하기
- Tensordot 연산 확인하기 223
- einsum 연산 확인하기

In [1]:
import numpy as np

- 산술 연산
    - 벡터 산술연산

In [2]:
# 벡터 간의 덧셈
d = np.array([3, 4])
e = np.array([5, 6])

print(d+e)
print()

print(np.add(d, e))
print

f = np.array([1, 2, 3])
try:
    f + e
except Exception as ex:
    print(ex)

[ 8 10]

[ 8 10]
operands could not be broadcast together with shapes (3,) (2,) 


In [3]:
# 벡터 간의 뺄셈
d = np.array([3, 4])
e = np.array([5, 6])

print(d-e)
print()

print(np.subtract(d, e))
print()

print(d+(-e))
print()

print(np.add(d, np.negative(e)))

[-2 -2]

[-2 -2]

[-2 -2]

[-2 -2]


In [4]:
# 스칼라 값을 벡터에 곱하기
d = np.array([2, 3])

print(3 * d)
print()

print(np.array([3, 3]) * 9)
print()

print(np.multiply(3, d))
print()

print(np.multiply(np.array([3, 3]), d))
print()

print(1/3 * d)
print()

print(np.divide(d, 3))
print()

print(np.multiply(d, (1/3)))

[6 9]

[27 27]

[6 9]

[6 9]

[0.66666667 1.        ]

[0.66666667 1.        ]

[0.66666667 1.        ]


- 산술 연산
    - 행렬의 산술연산

In [5]:
# 행렬의 산술연산
a = np.array([[3, 4], [4, 5]], dtype=np.int64)
print(a)
print()

b = np.array([[2, 4], [2, 5]], dtype='i8')
print(b)
print()

print(np.add(a, b))
print()

print(np.subtract(a, b))
print()

print(np.multiply(a, b))
print()

print(np.divide(a, b))
print()

print(np.floor_divide(a, b))
print()

print(np.divmod(a,b))

[[3 4]
 [4 5]]

[[2 4]
 [2 5]]

[[ 5  8]
 [ 6 10]]

[[1 0]
 [2 0]]

[[ 6 16]
 [ 8 25]]

[[1.5 1. ]
 [2.  1. ]]

[[1 1]
 [2 1]]

(array([[1, 1],
       [2, 1]]), array([[1, 0],
       [0, 0]]))


In [6]:
# 행렬에 스칼라 곱셈과 나눗셈 처리
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.multiply(3, d))
print()

s = np.full((3, 3), 3)
print(s)
print()

print(np.multiply(s, d))
print()

print(np.divide(3, d))
print()

print(np.floor_divide(d, 3))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

[[3 3 3]
 [3 3 3]
 [3 3 3]]

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

[[3.         1.5        1.        ]
 [0.75       0.6        0.5       ]
 [0.42857143 0.375      0.33333333]]

[[0 0 1]
 [1 1 2]
 [2 2 3]]


- 산술 연산
    - 대수의 법칙(law of algebra)

In [10]:
# 결합법칙
x = np.reshape(np.arange(4.0), (2, 2))
print(x)
print()

y = np.reshape(np.arange(6.0, 10.), (2, 2))
print(y)
print()

z = np.reshape(np.arange(12., 16.), (2, 2))
print(z)
print()

a = (x + y) + z
b = x + (y + z)
print(a == b)

[[0. 1.]
 [2. 3.]]

[[6. 7.]
 [8. 9.]]

[[12. 13.]
 [14. 15.]]

[[ True  True]
 [ True  True]]


In [12]:
# 분베법칙
c = x*(y+z)
d = (y+z)*x
c==d

array([[ True,  True],
       [ True,  True]])

In [13]:
# 교환법칙
f = x + y
g = y + x
print(f == g)
print()

i = x * y
j = y * x
print(i == j)

[[ True  True]
 [ True  True]]

[[ True  True]
 [ True  True]]


- 브로드캐스팅 이해하기
    - 브로드캐스팅(broadcasting) 이해하기

In [14]:
# 브로드캐스팅 내장함수 사용
x = np.arange(10).reshape(2, 5)
print(x)
print()

y = np.arange(5)
print(y)
print()

print(np.broadcast)
print(type(np.broadcast))
print()

z = np.broadcast(x, y)
print(z)
print()

print(type(z))
print(z.shape, z.ndim)
print()

for i in z:
    print(i)

[[0 1 2 3 4]
 [5 6 7 8 9]]

[0 1 2 3 4]

<class 'numpy.broadcast'>
<class 'type'>


<class 'numpy.broadcast'>
(2, 5) 2

(np.int64(0), np.int64(0))
(np.int64(1), np.int64(1))
(np.int64(2), np.int64(2))
(np.int64(3), np.int64(3))
(np.int64(4), np.int64(4))
(np.int64(5), np.int64(0))
(np.int64(6), np.int64(1))
(np.int64(7), np.int64(2))
(np.int64(8), np.int64(3))
(np.int64(9), np.int64(4))


In [15]:
z = np.broadcast(x, y)
b = np.empty(z.shape, int)
print(b.flat)
print()

b.flat = [i for _,i in z]
print(b)
print()

print(x+b)
print()
print(x+y)


[[0 1 2 3 4]
 [0 1 2 3 4]]

[[ 0  2  4  6  8]
 [ 5  7  9 11 13]]

[[ 0  2  4  6  8]
 [ 5  7  9 11 13]]


In [16]:
# 브로드캐스팅 내장함수 사용
a = np.array([1, 2, 3])
ax = np.broadcast_to(a, (3, 3))
print(ax)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [17]:
try:
    np.broadcast_to(a, (3, 4))
except Exception as e:
    print(e)

operands could not be broadcast together with remapped shapes [original->remapped]: (3,)  and requested shape (3,4)


In [20]:
a = np.broadcast_arrays(np.array([1, 2, 3, 4]), np.array([5, 6, 7, 8]))
print(a)
print()

b = np.broadcast_arrays(np.array([1, 2, 3, 4]), np.array([[5, 6, 7, 8], [7, 8, 9, 10]]))
print(b)

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

(array([[1, 2, 3, 4],
       [1, 2, 3, 4]]), array([[ 5,  6,  7,  8],
       [ 7,  8,  9, 10]]))


In [21]:
try:
    c = np.broadcast_arrays(np.array([1, 2, 3,4]), np.array([[5, 6, 7], [7, 8, 9]]))
except Exception as e:
    print(e)

shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (4,) and arg 1 with shape (2, 3).


In [22]:
c = np.broadcast_arrays(np.arange(3).reshape(1, 3), np.arange(3).reshape(3, 1), )
c

(array([[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]),
 array([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]))

In [23]:
# 브로드캐스팅 규칙 이해하기
x2 = np.ones((2, 3))
print(x2)
print()

x1 = np.ones(3)
print(x1)
print()

print(x1.shape, x2.shape)
print(x1.shape[0] == x2.shape[1])
print()

x1 = x1[np.newaxis, ]
print(x1.shape)
print()

x1 = np.vstack((x1[0], x1[0]))
print(x1)
print()

print(x1.shape == x2.shape)
print(x1 + x2)

[[1. 1. 1.]
 [1. 1. 1.]]

[1. 1. 1.]

(3,) (2, 3)
True

(1, 3)

[[1. 1. 1.]
 [1. 1. 1.]]

True
[[2. 2. 2.]
 [2. 2. 2.]]


- 브로드캐스팅 이해하기
    - 함수를 사용해서 브로드캐스팅

In [25]:
# 상위차원의 다른 경우
x = np.arange(1, 7).reshape(2, 3)
print(x)
print()

y = np.arange(1, 4)
print(y)
print()

print(x.ndim > y.ndim)
print(np.linalg.matrix_rank(x))
print(np.linalg.matrix_rank(y))
print()

z = np.broadcast_arrays(x, y)
print(z)
print()
print(z[0] + z[1])
print()
print(x + y)

[[1 2 3]
 [4 5 6]]

[1 2 3]

True
2
1

(array([[1, 2, 3],
       [4, 5, 6]]), array([[1, 2, 3],
       [1, 2, 3]]))

[[2 4 6]
 [5 7 9]]

[[2 4 6]
 [5 7 9]]


In [26]:
# 배열의 내부 형상에서 1이 존재
x = np.arange(1, 5).reshape(2, 2)
print(x)
print()

y = np.arange(1,3).reshape(1, 2)
print(y)
print()

z = np.broadcast_arrays(x, y)
print(z[0].shape == z[1].shape)
print(z)
print()

b = np.arange(1, 3).reshape(2, 1)
print(b)
print()

zb = np.broadcast_arrays(x, b)
print(zb)

[[1 2]
 [3 4]]

[[1 2]]

True
(array([[1, 2],
       [3, 4]]), array([[1, 2],
       [1, 2]]))

[[1]
 [2]]

(array([[1, 2],
       [3, 4]]), array([[1, 1],
       [2, 2]]))


- 브로드캐스팅 이해하기
    - 스칼라 브로드캐스팅 확장

In [27]:
# 스칼라에 대한 확장 처리
x = np.ones((2, 3))
print(x)
print()

y = np.array(10)
print(y)
print()

print(x.shape, y.shape)
print()

y = y[np.newaxis]
print(y)
print(y.shape)
print()

y = y[np.newaxis, :]
print(y)
print(y.shape)
print()

y = np.broadcast_to(y, (2,3))
print(y)
print()

print(x + y)
print()

print(10 + x)

[[1. 1. 1.]
 [1. 1. 1.]]

10

(2, 3) ()

[10]
(1,)

[[10]]
(1, 1)

[[10 10 10]
 [10 10 10]]

[[11. 11. 11.]
 [11. 11. 11.]]

[[11. 11. 11.]
 [11. 11. 11.]]


- 브로드캐스팅 이해하기
    - 행벡터와 열벡터 브로드캐스팅 확장

In [28]:
# 행벡터와 열벡터 확장 처리
x = np.arange(1, 4)
print(x)
print()

x1 = x.reshape(1, 3)
print(x1)
print()

x2 = x[np.newaxis, ]
print(x2)
print()

y = np.arange(1, 4)
print(y)
print()

y1 = y.reshape(3, 1)
print(y1)
print()

y2 = y[:, np.newaxis]
print(y2)
print()

print(np.broadcast_arrays(x1, y1))
print()

print(x1 + y1)

[1 2 3]

[[1 2 3]]

[[1 2 3]]

[1 2 3]

[[1]
 [2]
 [3]]

[[1]
 [2]
 [3]]

(array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]]), array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]]))

[[2 3 4]
 [3 4 5]
 [4 5 6]]


- 행렬의 연산
    - 벡터 내적 및 외적 구하기

In [29]:
# 벡터의 내적 이해하기
a = np.array([3, 4])
b = np.array([5, 6])

print(a@b)
print()
print(np.dot(a, b))
print()
print(np.inner(a,b))

39

39

39


In [33]:
# 벡터의 외적 이해하기
a = np.array([1, 4])
b = np.array([3, 6])

print(np.cross(a, b))
print()

c = np.array([1, 4, 3])
d = np.array([3, 4, 5])
print(np.cross(c, d))
print()

print(np.outer(a, b))
print()
print(np.outer(c, d))

-6

[ 8  4 -8]

[[ 3  6]
 [12 24]]

[[ 3  4  5]
 [12 16 20]
 [ 9 12 15]]


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27364\1608519651.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(a, b))


- 행렬의 연산
    - 행렬곱 연산: dot product

In [34]:
# 행렬의 닷연산
a = np.array([[3, 4], [5, 6]])
print(a)
print()

b = np.array([[5, 6], [6, 7]])
print(b)
print()

print(a.shape)
print(b.shape)
print(a.shape[1] == b.shape[0])
print()

print(np.dot(a, b))
print()
print(a.dot(b))
print()
print(a @ b)

[[3 4]
 [5 6]]

[[5 6]
 [6 7]]

(2, 2)
(2, 2)
True

[[39 46]
 [61 72]]

[[39 46]
 [61 72]]

[[39 46]
 [61 72]]


In [35]:
# 행렬을 분해해서 닷연산 하기
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 8]])

print(np.dot(a, b))
print()

c = b[:, 0]
d = b[:, 1]
e = b[:, 2]

c = c[:, np.newaxis]
d = d[:, np.newaxis]
e = e[:, np.newaxis]

print(c)
print()

f = a @ c
g = a @ d
h = a @ e

print(f)
print()

i = np.concatenate([f, g, h], axis=1)
print(i)
print()

print(np.matmul(a, b))
print()

try:
    np.matmul(a, 2)
except Exception as e:
    print(e)
    
print()
print(np.dot(a,2))

[[ 30  36  39]
 [ 66  81  90]
 [102 126 141]]

[[1]
 [4]
 [7]]

[[ 30]
 [ 66]
 [102]]

[[ 30  36  39]
 [ 66  81  90]
 [102 126 141]]

[[ 30  36  39]
 [ 66  81  90]
 [102 126 141]]

matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [36]:
# 행렬의 수직으로 닷연산을 하기
x = np.array([[3, 4], [5, 6]])
y = np.array([[2, 5], [7, 8]])
print(np.vdot(x, y))
print()

v1 = x[0, 0] * y[0, 0]
v2 = x[0, 1] * y[0, 1]
v3 = x[1, 0] * y[1, 0]
v4 = x[1, 1] * y[1, 1]
print(v1 + v2 + v3 + v4)
print()

a1 = np.array([[3+2j, 4+2j], [5+2j, 6+2j]])
a2 = np.array([[2+3j, 5+3j], [7+3j, 8+3j]])
print(np.vdot(a1, a2))
print(np.vdot(a2, a1))

109

109

(133+10j)
(133-10j)


- 행렬의 연산
    - 행렬 연산: inner/outer/cross

In [37]:
# 행렬의 inner 연산
a = np.array([[3, 4], [5, 6]])
print(a)
print()

b = np.array([[5, 6], [6, 7]])
print(b)
print()

print(np.dot(a, b[0]))
print()

print(np.dot(a, b[0].reshape(2,1)))
print()

print(np.dot(a, b[1]))
print()

print(np.dot(a, b[1].reshape(2, 1)))
print()

print(np.inner(a,b))
print()

print(np.dot(a,b))

[[3 4]
 [5 6]]

[[5 6]
 [6 7]]

[39 61]

[[39]
 [61]]

[46 72]

[[46]
 [72]]

[[39 46]
 [61 72]]

[[39 46]
 [61 72]]


In [38]:
# 행렬의 outer 연산
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 2], [3, 4]])

print(np.outer(a, b))
print()

c = np.outer(a, b[0])
d = np.outer(a, b[1])
print(np.concatenate([c, d], axis=1))

[[ 3  2  3  4]
 [ 6  4  6  8]
 [ 9  6  9 12]
 [12  8 12 16]]

[[ 3  2  3  4]
 [ 6  4  6  8]
 [ 9  6  9 12]
 [12  8 12 16]]


In [39]:
# 행렬의 cross 연산
x = np.array([[3, 4], [5, 6]])
y = np.array([[2, 5], [7, 8]])

print(np.cross(x, y))
print(np.cross(x[0], y[0]))
print(np.cross(x[1], y[1]))
print()

z1 = np.cross(x[0], y[0]).reshape(1)
z2 = np.cross(x[1], y[1]).reshape(1)
print(np.concatenate([z1, z2]))

[ 7 -2]
7
-2

[ 7 -2]


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27364\4279843495.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(x, y))
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27364\4279843495.py:6: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(x[0], y[0]))
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27364\4279843495.py:7: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(x[1], y[1]))
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27364\4279843495.py:10: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  z1 = np.cross(x[0], y[0]).reshape(1)
C:\U

- 행렬식, 역행렬 처리하기
    - 행렬식(determinant)

In [40]:
# 행렬식 구하기
a = np.array([[3, 1], [2, 2]])
print(np.linalg.det(a))
print(np.allclose(4.0, np.linalg.det(a)))

4.000000000000001
True


In [41]:
# 소행렬식 구하기
b = np.array([[3, 1, 3], [2, 2, 3], [1, 1, 1]])
print(b)
print()

print(3 * np.linalg.det(b[1:, 1:]))
print(np.linalg.det(b[1:, ::2]))
print(3 * np.linalg.det(b[1:, :2]))
print(np.linalg.det(b))
print(-3+1+0)

[[3 1 3]
 [2 2 3]
 [1 1 1]]

-3.0
-1.0
0.0
-2.0
-2


- 행렬식, 역행렬 처리하기
    - 역행렬(Inverse Matrix)

In [42]:
# 역행렬 구하기
a = np.array([[3, 2], [6, 4]])
print(np.linalg.det(a))
print()

b = np.array([[1, 2, 3], [4, 5, 6], [3, 2, 4]])
print(np.linalg.det(b))
print()

bi = np.linalg.inv(b)
bb = np.dot(b, bi)
print(np.allclose(np.eye(3), bb))

0.0

-9.000000000000002

True


In [43]:
# 역행렬의 교환법칙
a = np.array([[1, 2], [3, 4]])
print(a)
print()

ai = np.linalg.inv(a)
print(a)
print()

x = np.dot(a, ai)
print(x)
print()

print(np.allclose(np.eye(2), x))
print()

y = np.dot(ai, a)
print(y)
print()

print(np.allclose(np.eye(2), y))
print()

print(np.allclose(x, y))

[[1 2]
 [3 4]]

[[1 2]
 [3 4]]

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]

True

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]

True

True


- 행렬식, 역행렬 처리하기
    - 역행렬에 대한 분배 처리

In [46]:
# 역행렬기호 분배하기
a = np.array([[1, 2], [3, 4]])
print(np.linalg.det(a))
print()

b = np.array([[3, 4], [1, 2]])
print(np.linalg.det(b))
print()

ai = np.linalg.inv(a)
bi = np.linalg.inv(b)

ab = np.linalg.inv(np.dot(a, b))
ba = np.dot(bi, ai)
print(np.allclose(ab, ba))

-2.0000000000000004

2.0000000000000004

True


In [47]:
# 두 행렬 처리 알아보기
print(a)
print()

print(b)
print()

c = np.dot(a, b)

print(bi)
print()
print(ai)
print()

d = np.dot(bi, ai)
e = np.dot(c, d)
print(e)

[[1 2]
 [3 4]]

[[3 4]
 [1 2]]

[[ 1.  -2. ]
 [-0.5  1.5]]

[[-2.   1. ]
 [ 1.5 -0.5]]

[[1. 0.]
 [0. 1.]]


- 행렬식, 역행렬 처리하기
    - 수반행렬(Adjoint, Adjugated Matrix)

In [48]:
# 소행렬식
ma = np.arange(1, 10).reshape(3, 3)
print(ma)
print()

print(list(range(10)))
print()

a = np.array(list(range(0)) + list(range(1, 3)))[:, np.newaxis]
print(a)
print()

b = np.array(list(range(0)) + list(range(1, 3)))
print(b)
print()

ja = ma[a, b]
print(ja)
print()

print(np.linalg.det(ja))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

[[1]
 [2]]

[1 2]

[[5 6]
 [8 9]]

-2.9999999999999996


In [49]:
# 여인수 알아보기: 역행렬을 구하기위해서 계산
cofactor = (-1)**(0+0) * np.linalg.det(ja)
print(cofactor)

-2.9999999999999996


- 행렬식, 역행렬 처리하기
    - 의사 역행렬

In [50]:
# 의사 역행렬
a = np.ones((3, 3))

print(np.linalg.det(a))
print()

print(np.linalg.pinv(a))
print()

try:
    np.linalg.inv(a)
except Exception as e:
    print(e)

0.0

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]

Singular matrix


- Tensordot 연산 확인하기
    - 벡터와 행렬연산을 tesordot 연산 확인하기

In [51]:
# 닷 연산 확인하기
x = np.random.randint(1, 10, (2, 2))
print(x)
print()

y = np.random.randint(1, 10, (2, 2))
print(y)
print()

print(np.dot(x, y))
print()

print(np.tensordot(x, y, axes=1))
print()

print(np.inner(x, y))
print()

print(np.tensordot(x, y, axes=(-1, -1)))

[[1 6]
 [3 1]]

[[8 8]
 [2 4]]

[[20 32]
 [26 28]]

[[20 32]
 [26 28]]

[[56 26]
 [32 10]]

[[56 26]
 [32 10]]


- Tensordot 연산 확인하기
    - 확장하는 텐서곱 연산

In [53]:
# 텐서 프로덕트
x = np.random.randint(1, 10, (2, 2))

print(x)
print()

y = np.random.randint(1, 10, (2, 2))
print(y)
print()

a = np.tensordot(x, y, axes=0)
print(a.shape)
print()
print(a)

[[5 4]
 [7 8]]

[[4 2]
 [9 3]]

(2, 2, 2, 2)

[[[[20 10]
   [45 15]]

  [[16  8]
   [36 12]]]


 [[[28 14]
   [63 21]]

  [[32 16]
   [72 24]]]]


- Tensordot 연산 확인하기
    - 축소하는 텐서곱 연산(tensor double contraction)

In [54]:
# 텐서 더블 컨트랙트
x = np.random.randint(1, 10, (2, 2))
print(x)
print()

y = np.random.randint(1, 10, (2, 2))
print(y)
print()

a = np.tensordot(x, y, axes=2)
print(a.shape)
print(a)

[[9 2]
 [5 3]]

[[9 4]
 [7 5]]

()
139


In [55]:
c = np.random.randint(1, 10, (2, 2, 2))
print(c)
print()

d = np.random.randint(1, 10, (2, 2, 2))
print(d)
print()

print(np.dot(c.reshape(2, 4), d.reshape(4, 2)))
print()

b = np.tensordot(c, d, axes=2)
print(b)

[[[7 7]
  [4 2]]

 [[1 6]
  [5 5]]]

[[[5 7]
  [1 4]]

 [[3 7]
  [5 6]]]

[[ 64 117]
 [ 51  96]]

[[ 64 117]
 [ 51  96]]


- Tensordot 연산 확인하기
    - kron 연산 처리하기

In [57]:
# kron 함수 처리하기
ll = np.arange(1, 4)
ls = np.array([10, 20, 30])

print(np.kron(ll, ls))
print()

ll_ = np.repeat(ll, 3)
print(ll_)
print()

ls_ = np.tile(ls, 3)
print(ls_)
print(ll_ * ls_)
print()
print(np.outer(ll, ls))

[10 20 30 20 40 60 30 60 90]

[1 1 1 2 2 2 3 3 3]

[10 20 30 10 20 30 10 20 30]
[10 20 30 20 40 60 30 60 90]

[[10 20 30]
 [20 40 60]
 [30 60 90]]


In [58]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
print(x)
print()

y = np.eye(2)
print(y)
print()

print(np.kron(x, y))
print()

x_ = np.repeat(x, 2, axis=0)
print(x_)
print()

x_ = np.repeat(x_, 2, axis=1)
print(x_)
print()

y_ = np.tile(y, (2, 2))
print(y_)
print()

[[1 2]
 [3 4]]

[[1. 0.]
 [0. 1.]]

[[1. 0. 2. 0.]
 [0. 1. 0. 2.]
 [3. 0. 4. 0.]
 [0. 3. 0. 4.]]

[[1 2]
 [1 2]
 [3 4]
 [3 4]]

[[1 1 2 2]
 [1 1 2 2]
 [3 3 4 4]
 [3 3 4 4]]

[[1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]



In [59]:
print(np.multiply(x_, y_))
print()

print(x.reshape(4, 1))
print()
print(y.reshape(1, 4))
print()
print(np.outer(x, y))
print()
print(np.dot(x.reshape(4, 1), y.reshape(1, 4)))

[[1. 0. 2. 0.]
 [0. 1. 0. 2.]
 [3. 0. 4. 0.]
 [0. 3. 0. 4.]]

[[1]
 [2]
 [3]
 [4]]

[[1. 0. 0. 1.]]

[[1. 0. 0. 1.]
 [2. 0. 0. 2.]
 [3. 0. 0. 3.]
 [4. 0. 0. 4.]]

[[1. 0. 0. 1.]
 [2. 0. 0. 2.]
 [3. 0. 0. 3.]
 [4. 0. 0. 4.]]


- einsum 연산 확인하기
    - 하나의 배열을 변경하기

In [60]:
# 하나 배열의 연산 처리하기
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print()
print(A.T)
print()
print(np.einsum("ij->ji", A))
print()

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]



In [61]:
AA = np.arange(10)
print(np.einsum('i->', AA))
print()
print(np.sum(AA))

45

45


In [62]:
A__ = np.array([[1, 1, 1], [3, 2, 4], [7, 5, 8]])
print(np.einsum("ij->", A__))
print(np.sum(A__))

32
32


In [63]:
print(np.einsum("ij->i", A__))
print()
print(np.sum(A__, axis=1))
print()

print(np.einsum("ij->j", A__))
print()
print(np.sum(A__, axis=0))

[ 3  9 20]

[ 3  9 20]

[11  8 13]

[11  8 13]


In [64]:
print(np.einsum("ii", A__))
print(np.einsum("ii->", A__))
print(np.trace(A__))

11
11
11


In [65]:
print(np.einsum("ii->i", A__))
print(np.diag(A__))

[1 2 8]
[1 2 8]


- einsum 연산 확인하기
    - 두 개의 1차원 배열 연산을 알아보기

In [66]:
# 두 개 1차원 배열의 연산 처리하기
C = np.arange(10)
D = np.arange(5, 15)

print(np.einsum('i,i->i', C, D))
print(np.einsum('i,i->', C, D))
print(np.dot(C, D))
print(np.einsum('i,j->', C, D))

[  0   6  14  24  36  50  66  84 104 126]
510
510
4275


In [68]:
print(C.reshape(10, 1).repeat(10, axis=1))
print()

print(np.dot(C.reshape(10,1).repeat(10, axis=1), D.reshape(10,1)).T[0])
print()

print(np.einsum('i,j->j', C, D))
print()

print(D.reshape(1, 10).repeat(10, axis=0))
print()
print(np.dot(C.reshape(1, 10), D.reshape(1, 10).repeat(10, axis=0))[0])

[[0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1]
 [2 2 2 2 2 2 2 2 2 2]
 [3 3 3 3 3 3 3 3 3 3]
 [4 4 4 4 4 4 4 4 4 4]
 [5 5 5 5 5 5 5 5 5 5]
 [6 6 6 6 6 6 6 6 6 6]
 [7 7 7 7 7 7 7 7 7 7]
 [8 8 8 8 8 8 8 8 8 8]
 [9 9 9 9 9 9 9 9 9 9]]

[  0  95 190 285 380 475 570 665 760 855]

[225 270 315 360 405 450 495 540 585 630]

[[ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]]

[225 270 315 360 405 450 495 540 585 630]


In [70]:
print(np.einsum('i,j->ij', C, D))
print()

print(np.outer(C, D))
print()

print(np.dot(C.reshape(10,1), D.reshape(1, 10)))
print()

print(np.einsum('i,j->ji', C, D))
print()

print(np.outer(D.reshape(10, 1), C.reshape(1, 10)))

[[  0   0   0   0   0   0   0   0   0   0]
 [  5   6   7   8   9  10  11  12  13  14]
 [ 10  12  14  16  18  20  22  24  26  28]
 [ 15  18  21  24  27  30  33  36  39  42]
 [ 20  24  28  32  36  40  44  48  52  56]
 [ 25  30  35  40  45  50  55  60  65  70]
 [ 30  36  42  48  54  60  66  72  78  84]
 [ 35  42  49  56  63  70  77  84  91  98]
 [ 40  48  56  64  72  80  88  96 104 112]
 [ 45  54  63  72  81  90  99 108 117 126]]

[[  0   0   0   0   0   0   0   0   0   0]
 [  5   6   7   8   9  10  11  12  13  14]
 [ 10  12  14  16  18  20  22  24  26  28]
 [ 15  18  21  24  27  30  33  36  39  42]
 [ 20  24  28  32  36  40  44  48  52  56]
 [ 25  30  35  40  45  50  55  60  65  70]
 [ 30  36  42  48  54  60  66  72  78  84]
 [ 35  42  49  56  63  70  77  84  91  98]
 [ 40  48  56  64  72  80  88  96 104 112]
 [ 45  54  63  72  81  90  99 108 117 126]]

[[  0   0   0   0   0   0   0   0   0   0]
 [  5   6   7   8   9  10  11  12  13  14]
 [ 10  12  14  16  18  20  22  24  26  28]
 [ 15  

- einsum 연산 확인하기
    - 두 개의 2차원 배열 연산을 알아보기

In [72]:
# 두 개의 2차원 배열 연산 처리하기
E = np.arange(10).reshape(2, 5)
F = np.arange(5, 15).reshape(2, 5)

print(np.einsum('ij,ij->ij', E, F))
print()

print(np.einsum('ij,jk->ik', E, F.T))
print()

print(np.dot(E, F.T))

[[  0   6  14  24  36]
 [ 50  66  84 104 126]]

[[ 80 130]
 [255 430]]

[[ 80 130]
 [255 430]]


In [74]:
A_ = np.array([0, 1, 2])
B_ = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])

print(np.einsum('i,ij->', A_, B_))
print()

print(np.sum(A_) + np.sum(B_))
print()

print((A_.reshape(3, 1) * B_).sum())
print()

print(A_[:, np.newaxis])

98

69

98

[[0]
 [1]
 [2]]


In [75]:
print(A_[:, np.newaxis] * B_)
print()

print((A_[:, np.newaxis] * B_).sum())
print()

print(np.einsum('i,ij->i', A_, B_))
print()

print((A_[:, np.newaxis]*B_).sum())
print()

print(np.einsum('i,ij->j', A_, B_))
print()

print((A_[:, np.newaxis] * B_).sum(axis=0))

[[ 0  0  0  0]
 [ 4  5  6  7]
 [16 18 20 22]]

98

[ 0 22 76]

98

[20 23 26 29]

[20 23 26 29]


In [76]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
print(x.T)
print()

try:
    np.einsum('ii,ii->ii', x, x)
except Exception as e:
    print(e)

[[1 3]
 [2 4]]

einstein sum subscripts string includes output subscript 'i' multiple times


In [77]:
print(np.einsum('ij, ij->ij', x, x))
print()

print(x * x)
print()

print(np.einsum('ij, ij->ij', x, x))
print()

print(x * x.T)
print()

print(np.einsum('ij,jk->ik', x, x.T))
print()

print(np.dot(x, x.T))
print()

[[ 1  4]
 [ 9 16]]

[[ 1  4]
 [ 9 16]]

[[ 1  4]
 [ 9 16]]

[[ 1  6]
 [ 6 16]]

[[ 5 11]
 [11 25]]

[[ 5 11]
 [11 25]]

