### Tensor 이해
- Tansor란?
    - pytorch에서 데이터를 저장하는 객체
    - model input/output data shape
- torch version:

In [3]:
import torch

print(f"fotch v.{torch.__version__}")

fotch v.2.4.1


In [2]:
# 텐서 속성 정보 추력 함수

def printInfo(obj, obj_name):
    print(f"\n[{obj_name}]")
    print(f"shape: {obj.shape}")
    print(f"ndim: {obj.ndim}D")
    print(f"dtype: {obj.dtype}")
    print(f"device: {obj.device}")
    print(f"data:\n{obj.data}")

In [4]:
# tensor data
ten1 = torch.tensor(10)
ten2 = torch.tensor([22, 33, 44])
ten3 = torch.tensor([[90, 91], [80, 81], [70, 71]])

In [5]:
# print
printInfo(ten1, 'ten1')
printInfo(ten2, 'ten2')
printInfo(ten3, 'ten3')


[ten1]
shape: torch.Size([])
ndim: 0D
dtype: torch.int64
device: cpu
data:
10

[ten2]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int64
device: cpu
data:
tensor([22, 33, 44])

[ten3]
shape: torch.Size([3, 2])
ndim: 2D
dtype: torch.int64
device: cpu
data:
tensor([[90, 91],
        [80, 81],
        [70, 71]])


In [9]:
# 0D, skala
data_tf = torch.tensor(10)
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor(10, dtype=torch.int8)
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor(10, dtype=torch.uint8)
printInfo(data_tf, 'data_tf')


[data_tf]
shape: torch.Size([])
ndim: 0D
dtype: torch.int64
device: cpu
data:
10

[data_tf]
shape: torch.Size([])
ndim: 0D
dtype: torch.int8
device: cpu
data:
10

[data_tf]
shape: torch.Size([])
ndim: 0D
dtype: torch.uint8
device: cpu
data:
10


In [10]:
# 1D, vector
data_tf = torch.tensor([10])
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor([10], dtype=torch.int8)
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor([10], dtype=torch.uint8)
printInfo(data_tf, 'data_tf')


[data_tf]
shape: torch.Size([1])
ndim: 1D
dtype: torch.int64
device: cpu
data:
tensor([10])

[data_tf]
shape: torch.Size([1])
ndim: 1D
dtype: torch.int8
device: cpu
data:
tensor([10], dtype=torch.int8)

[data_tf]
shape: torch.Size([1])
ndim: 1D
dtype: torch.uint8
device: cpu
data:
tensor([10], dtype=torch.uint8)


In [11]:
# 2D, matrix
data_tf = torch.tensor([[10]])
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor([[10, 10]], dtype=torch.int8)
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor([[10]], dtype=torch.uint8)
printInfo(data_tf, 'data_tf')


[data_tf]
shape: torch.Size([1, 1])
ndim: 2D
dtype: torch.int64
device: cpu
data:
tensor([[10]])

[data_tf]
shape: torch.Size([1, 2])
ndim: 2D
dtype: torch.int8
device: cpu
data:
tensor([[10, 10]], dtype=torch.int8)

[data_tf]
shape: torch.Size([1, 1])
ndim: 2D
dtype: torch.uint8
device: cpu
data:
tensor([[10]], dtype=torch.uint8)


In [12]:
# 3D, tensor
data_tf = torch.tensor([[[10]]])
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor([[[10]]], dtype=torch.int8)
printInfo(data_tf, 'data_tf')

data_tf = torch.tensor([[[10]]], dtype=torch.uint8)
printInfo(data_tf, 'data_tf')


[data_tf]
shape: torch.Size([1, 1, 1])
ndim: 3D
dtype: torch.int64
device: cpu
data:
tensor([[[10]]])

[data_tf]
shape: torch.Size([1, 1, 1])
ndim: 3D
dtype: torch.int8
device: cpu
data:
tensor([[[10]]], dtype=torch.int8)

[data_tf]
shape: torch.Size([1, 1, 1])
ndim: 3D
dtype: torch.uint8
device: cpu
data:
tensor([[[10]]], dtype=torch.uint8)


In [6]:
# 0으로 채운 tensor
zten1 = torch.zeros(2, 5)
zten2 = torch.zeros(3)

printInfo(zten1, 'zten1')
printInfo(zten2, 'zten2')


[zten1]
shape: torch.Size([2, 5])
ndim: 2D
dtype: torch.float32
device: cpu
data:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

[zten2]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float32
device: cpu
data:
tensor([0., 0., 0.])


In [8]:
# 1로 채운 tensor
oten1 = torch.ones(2, 3)
oten2 = torch.ones(3)

printInfo(oten1, 'oten1')
printInfo(oten2, 'oten2')


[oten1]
shape: torch.Size([2, 3])
ndim: 2D
dtype: torch.float32
device: cpu
data:
tensor([[1., 1., 1.],
        [1., 1., 1.]])

[oten2]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float32
device: cpu
data:
tensor([1., 1., 1.])


In [13]:
# attibute value tensor
ften1 = torch.full((3, ), 10)
ften2 = torch.full((3, 2), 10)

printInfo(ften1, 'ften1')
printInfo(ften2, 'ften2')


[ften1]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int64
device: cpu
data:
tensor([10, 10, 10])

[ften2]
shape: torch.Size([3, 2])
ndim: 2D
dtype: torch.int64
device: cpu
data:
tensor([[10, 10],
        [10, 10],
        [10, 10]])


In [14]:
# 대각선 tensor
eten1 = torch.eye(3)
eten2 = torch.eye(3, 5)

printInfo(eten1, 'eten1')
printInfo(eten2, 'eten2')


[eten1]
shape: torch.Size([3, 3])
ndim: 2D
dtype: torch.float32
device: cpu
data:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

[eten2]
shape: torch.Size([3, 5])
ndim: 2D
dtype: torch.float32
device: cpu
data:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
