### Tensor 이해_5
- Tansor란?
    - pytorch에서 데이터를 저장하는 객체
    - model input/output data shape
- torch version: 2.4.1

In [1]:
import torch
import numpy as np

print(f" torch version: {torch.__version__}")

 torch version: 2.4.1


In [2]:
# 텐서 속성 정보 출력 함수

def printInfo(obj, obj_name):
    print(f"\n[{obj_name}]")
    print(f"shape: {obj.shape}")
    print(f"ndim: {obj.ndim}D")
    print(f"dtype: {obj.dtype}")
    try:
        print(f"device: {obj.device}")
    except:
        pass
    print(f"data:\n{obj.data}")

- type casting
    - torch.type()
    - torch.type_name
    - torch.to(torch.type_name)

In [3]:
data_ts1 = torch.tensor([1, 3, 5])

printInfo(data_ts1, 'data_ts1')


[data_ts1]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int64
device: cpu
data:
tensor([1, 3, 5])


In [4]:
data_ts11 = data_ts1.type(torch.float32)

printInfo(data_ts11, 'data_ts11')


[data_ts11]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float32
device: cpu
data:
tensor([1., 3., 5.])


In [5]:
# int64 --> float
data_ts11 = data_ts1.float()

printInfo(data_ts11, 'data_ts11')


[data_ts11]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float32
device: cpu
data:
tensor([1., 3., 5.])


In [6]:
data_ts11 = data_ts1.bool()

printInfo(data_ts11, 'data_ts11')


[data_ts11]
shape: torch.Size([3])
ndim: 1D
dtype: torch.bool
device: cpu
data:
tensor([True, True, True])


In [7]:
data_ts11 = data_ts1.to(dtype=torch.int8)

printInfo(data_ts11, 'data_ts11')


[data_ts11]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int8
device: cpu
data:
tensor([1, 3, 5], dtype=torch.int8)


In [8]:
data_ts11 = data_ts1.to(dtype=torch.int8,
                        device='cuda' if torch.cuda.is_available() else 'cpu')
# 'cuda' if torch.cuda.is_available() else 'cpu' 없이 device를 바꾸려도 하면 오류 발생

printInfo(data_ts11, 'data_ts11')


[data_ts11]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int8
device: cpu
data:
tensor([1, 3, 5], dtype=torch.int8)


In [9]:
data_ts11[1], data_ts1[-1]

(tensor(3, dtype=torch.int8), tensor(5))

In [12]:
data_ts1[:2]

tensor([1, 3])

In [13]:
data_ts11 * 10

tensor([10, 30, 50], dtype=torch.int8)

In [16]:
data_ts11 + np.array([1, 2, 2])     # broadcastiong 어케 하더라?

tensor([2, 5, 7], dtype=torch.int32)

In [23]:
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
m3 = m1 + m2
print(m3, m3.shape)

tensor([[4., 5.]]) torch.Size([1, 2])
