### Tensor 이해_2
- Tansor란?
    - pytorch에서 데이터를 저장하는 객체
    - model input/output data shape
- torch version: 2.4.1

In [2]:
import torch

torch.__version__

'2.4.1'

In [3]:
# 텐서 속성 정보 추력 함수

def printInfo(obj, obj_name):
    print(f"\n[{obj_name}]")
    print(f"shape: {obj.shape}")
    print(f"ndim: {obj.ndim}D")
    print(f"dtype: {obj.dtype}")
    print(f"device: {obj.device}")
    print(f"data:\n{obj.data}")

In [21]:
# - value range: 0 <= x < 1, [0, 1)
# torch.rand(*size): 가변인자로 크기를 받음. 몇 차원인지 모르는까.

torch.manual_seed(125)  # random.see(125)

rten1 = torch.rand(2, 3)    # 숫자 1게: 1차원, 2개: 2차원, 3개: 3차원, ...

printInfo(rten1, 'rtend1')


[rtend1]
shape: torch.Size([2, 3])
ndim: 2D
dtype: torch.float32
device: cpu
data:
tensor([[0.7219, 0.3854, 0.7279],
        [0.1047, 0.6605, 0.7745]])


In [34]:
# - value range: mean(0), std(1)
# torch.randn()
torch.manual_seed(135)

rten2 = torch.randn(2, 3)

printInfo(rten2, 'rten2')


[rten2]
shape: torch.Size([2, 3])
ndim: 2D
dtype: torch.float32
device: cpu
data:
tensor([[-0.4099,  0.2912,  0.4471],
        [ 0.8840,  0.5042, -1.3501]])


In [35]:
# - value range: [low, high)
# torch.randint(low, high, size(=shape))
torch.manual_seed(136)

rten3 = torch.randint(1, 5, (2, 4))

printInfo(rten3, 'rten3')


[rten3]
shape: torch.Size([2, 4])
ndim: 2D
dtype: torch.int64
device: cpu
data:
tensor([[4, 2, 3, 2],
        [3, 2, 4, 3]])
