### Tensor 이해_4
- Tansor란?
    - pytorch에서 데이터를 저장하는 객체
    - model input/output data shape
- torch version: 2.4.1

In [9]:
import torch
import numpy as np

print(f"torch version: {torch.__version__}")

torch version: 2.4.1


In [11]:
# 텐서 속성 정보 추력 함수

def printInfo(obj, obj_name):
    print(f"\n[{obj_name}]")
    print(f"shape: {obj.shape}")
    print(f"ndim: {obj.ndim}D")
    print(f"dtype: {obj.dtype}")
    try:
        print(f"device: {obj.device}")
    except:
        pass
    print(f"data:\n{obj.data}")

In [5]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(DEVICE)

cpu


- python --> tensor

In [2]:
data = [x for x in range(1, 10)]

In [6]:
# list to tensor
data_ts = torch.as_tensor(data, dtype=torch.int8)

printInfo(data_ts, 'data_ts')


[data_ts]
shape: torch.Size([9])
ndim: 1D
dtype: torch.int8
device: cpu
data:
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)


In [8]:
data[0] = 100
data, data_ts   # view method? copy method?

([100, 2, 3, 4, 5, 6, 7, 8, 9],
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8))

In [12]:
# ndarray to tensor
arr1 = np.array([1, 2, 3])

arr1_ts = torch.as_tensor(arr1)

printInfo(arr1, 'arr1')
printInfo(arr1_ts, 'arr1_ts')


[arr1]
shape: (3,)
ndim: 1D
dtype: int32
data:

[arr1_ts]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int32
device: cpu
data:
tensor([1, 2, 3], dtype=torch.int32)


In [14]:
arr1_ts[0] = 99

arr1, arr1_ts   # view method...?, torch.as_tensor, torch.from_numpy 둘은 다른 겨?

tensor([99,  2,  3], dtype=torch.int32)

In [19]:
arr1[2] = 20

arr1, arr1_ts

(array([99,  2, 20]), tensor([99,  2, 20], dtype=torch.int32))

In [17]:
arr2 = np.array([3, 4, 5])
arr2_ts = torch.from_numpy(arr2)

printInfo(arr2, 'arr2')
print(arr2)
printInfo(arr2_ts, 'arr2_ts')


[arr2]
shape: (3,)
ndim: 1D
dtype: int32
data:
[3 4 5]

[arr2_ts]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int32
device: cpu
data:
tensor([3, 4, 5], dtype=torch.int32)


In [18]:
arr2_ts[0] = 100

arr2, arr2_ts

(array([100,   4,   5]), tensor([100,   4,   5], dtype=torch.int32))

In [20]:
arr2[1] = 80

arr2, arr2_ts

(array([100,  80,   5]), tensor([100,  80,   5], dtype=torch.int32))

##### default가 view method..?
- tensor를 부르는데 형태가 다르다고 하면 cpoy를 주고 아니면 view를 주는 듯
- 그래서 dtype을 다르게 지정하면 sharing 함.

In [21]:
arr3 = np.array([3, 6, 9])
arr3_ts = torch.as_tensor(arr3, dtype=torch.int8)

printInfo(arr3, 'arr3')
print(arr3)
printInfo(arr3_ts, 'arr3_ts')


[arr3]
shape: (3,)
ndim: 1D
dtype: int32
data:
[3 6 9]

[arr3_ts]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int8
device: cpu
data:
tensor([3, 6, 9], dtype=torch.int8)


In [22]:
arr3[0] = 30

arr3, arr3_ts   # copy method

(array([30,  6,  9]), tensor([3, 6, 9], dtype=torch.int8))

In [23]:
arr3_ts[1] = 30

arr3, arr3_ts

(array([30,  6,  9]), tensor([ 3, 30,  9], dtype=torch.int8))

In [33]:
arr4 = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float16)
arr4_ts = torch.from_numpy(arr4[0]) # create tensor

printInfo(arr4, 'arr4')
print(arr4)
print(f"attribute size: {arr4.size}")
print(f"attribute itemsize: {arr4.itemsize}")
print(f"방향: {arr4.strides}")
printInfo(arr4_ts, 'arr4_ts')


[arr4]
shape: (2, 3)
ndim: 2D
dtype: float16
data:
[[1. 2. 3.]
 [4. 5. 6.]]
attribute size: 6
attribute itemsize: 2
방향: (6, 2)

[arr4_ts]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float16
device: cpu
data:
tensor([1., 2., 3.], dtype=torch.float16)


In [28]:
arr4_ts[1] = 3

arr4, arr4_ts      # only view method? - yes. share the same memory

(array([[1., 3., 3.],
        [4., 5., 6.]], dtype=float32),
 tensor([1., 3., 3.]))

- data sharing
    - torch.as_tensor()
    - torch.from_numpy()
- data copy
    - torch.tensor()
    - torch.Tensor()