### Tensor 이해_7
- torch version: 2.4.1
- tensor reshape
    - tensor.reshape
    - tensor.view
    - tensor.transpose(axis): 2개dlm axis를 맞교환하여 reshaped tensor reurn
    - tensor.permute(axis): 모든 axis를 맞교환 하여 reshaped tensor return
    - torch.squeeze(tensor): 1인 차원을 모두 제거하여 tensor reshape
    - tensor.squeeze(dim): 지정된 차원에 1인 차원을 생성하여 tensor reshape
    - Contuguous
        - is_contiguous(): 연속성 여부
        - contiguous(): 연속성을 가지도록 만듦?

In [1]:
import torch
import numpy as np

print(f"torch version: {torch.__version__}")

torch version: 2.4.1


In [2]:
# 텐서 속성 정보 출력 함수

def printInfo(obj, obj_name):
    print(f"\n[{obj_name}]")
    print(f"shape: {obj.shape}")
    print(f"ndim: {obj.ndim}D")
    print(f"dtype: {obj.dtype}")
    try:
        print(f"device: {obj.device}")
    except:
        pass
    print(f"data:\n{obj.data}")

In [13]:
# tensor storage info print function
def printStorage(obj, obj_name):
    print(f"\n===[{obj_name}]===")
    print(f"{obj_name} : {obj}")
    print(f"shape   : {obj.shape}")
    print(f"ndim    : {obj.ndim}D")
    print(f"dtype   : {obj.dtype}")
    print(f"itemsize: {obj.itemsize}\n")
    
    print("=== STORAGE ===")
    print(f"offset: {obj.storage_offset()}")
    print(f"strides: {obj.stride()}") 
    print('='*15)
    print(obj.untyped_storage())  

In [20]:
data_ts = torch.arange(1, 21, dtype=torch.int8)

printStorage(data_ts, 'data_ts')


===[data_ts]===
data_ts : tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20], dtype=torch.int8)
shape   : torch.Size([20])
ndim    : 1D
dtype   : torch.int8
itemsize: 1

=== STORAGE ===
offset: 0
strides: (1,)
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.UntypedStorage(device=cpu) of size 20]


In [25]:
# 1D -> 2D
data_ts2 = data_ts.reshape((-1, 5))

printStorage(data_ts2, 'data_ts2')


===[data_ts2]===
data_ts2 : tensor([[77,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]], dtype=torch.int8)
shape   : torch.Size([4, 5])
ndim    : 2D
dtype   : torch.int8
itemsize: 1

=== STORAGE ===
offset: 0
strides: (5, 1)
 77
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.UntypedStorage(device=cpu) of size 20]


In [22]:
data_ts2[0][0] = 77
data_ts2

tensor([[77,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]], dtype=torch.int8)

In [43]:
data_ts[0] = 1
data_ts

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20], dtype=torch.int8)

In [44]:
data_ts22 = data_ts2.reshape((-1, 2))

printStorage(data_ts22, 'data_ts22')


===[data_ts22]===
data_ts22 : tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]], dtype=torch.int8)
shape   : torch.Size([10, 2])
ndim    : 2D
dtype   : torch.int8
itemsize: 1

=== STORAGE ===
offset: 0
strides: (2, 1)
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
[torch.storage.UntypedStorage(device=cpu) of size 20]


In [48]:
print(f"data_ts2 is_coutuguous() : {data_ts22.is_contiguous()}")
data_ts2

data_ts2 is_coutuguous() : True


tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]], dtype=torch.int8)

In [49]:
print(f"data_ts22 is_coutuguous() : {data_ts22.is_contiguous()}")
data_ts22

data_ts22 is_coutuguous() : True


tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]], dtype=torch.int8)

In [52]:
data_ts23 = data_ts22.T
print(f"data_ts23 is_coutuguous(): {data_ts22.T.is_contiguous()}")
data_ts23

data_ts23 is_coutuguous(): False


tensor([[ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19],
        [ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20]], dtype=torch.int8)

- 우리 눈에 보여지는 순서와 실제 데이터가 들어가있는 메모리 순서는 다른 -> 불연속적이다
    - 연속적으로 만들어야함

In [53]:
# 불연속적 -> 연속적
# tensor.contuguous()
# copy method... view method에서 연속성이 깨지는 문제 발생
d_ts = data_ts23.contiguous()
d_ts.storage()

 1
 3
 5
 7
 9
 11
 13
 15
 17
 19
 2
 4
 6
 8
 10
 12
 14
 16
 18
 20
[torch.storage.TypedStorage(dtype=torch.int8, device=cpu) of size 20]