### Tensor 이해_3
- Tansor란?
    - pytorch에서 데이터를 저장하는 객체
    - model input/output data shape
- torch version: 2.4.1

In [2]:
import torch

print(f"torch version: {torch.__version__}")

torch version: 2.4.1


In [3]:
# 텐서 속성 정보 추력 함수

def printInfo(obj, obj_name):
    print(f"\n[{obj_name}]")
    print(f"shape: {obj.shape}")
    print(f"ndim: {obj.ndim}D")
    print(f"dtype: {obj.dtype}")
    print(f"device: {obj.device}")
    print(f"data:\n{obj.data}")

- type 지정 tensor
    - data type을 설정 후 생성: data type을 알고 있다는 전제, 또는 형식 바꿀 때
    - data shpe 설정한 tensor 생성시
    - data의 자료형 변환한 tensor 생성시 사용

In [4]:
# randomly data
data = [1.4, 2.8, 3.1]

In [6]:
# integer type tensor create

data_ts1 = torch.CharTensor(data)
data_ts2 = torch.tensor(data, dtype=torch.int8)


printInfo(data_ts1, 'data_ts1')
printInfo(data_ts2, 'data_ts2')


[data_ts1]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int8
device: cpu
data:
tensor([1, 2, 3], dtype=torch.int8)

[data_ts2]
shape: torch.Size([3])
ndim: 1D
dtype: torch.int8
device: cpu
data:
tensor([1, 2, 3], dtype=torch.int8)


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_11960\2607046671.py:3: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  data_ts1 = torch.CharTensor(data)
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_11960\2607046671.py:4: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  data_ts2 = torch.tensor(data, dtype=torch.int8)


- 캐스팅 하는 함수가 있음
- 지금은 캐스팅에 오류가 발생할 수 있고 추후에는 없어질 기능이니까
- 사아용하지 말라는 것임

In [8]:
data2 = [0, -3, 11]

In [9]:
# logical tensor create
data_ts1 = torch.BoolTensor(data)
data_ts2 = torch.tensor(data2, dtype=torch.bool)

printInfo(data_ts1, 'data_ts1')
printInfo(data_ts2, 'data_ts2')


[data_ts1]
shape: torch.Size([3])
ndim: 1D
dtype: torch.bool
device: cpu
data:
tensor([True, True, True])

[data_ts2]
shape: torch.Size([3])
ndim: 1D
dtype: torch.bool
device: cpu
data:
tensor([False,  True,  True])


In [10]:
# real number tensor
data_ts1 = torch.DoubleTensor(data)
data_ts2 = torch.tensor(data, dtype=torch.float64)

printInfo(data_ts1, 'data_ts1')
printInfo(data_ts2, 'data_ts2')


[data_ts1]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float64
device: cpu
data:
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)

[data_ts2]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float64
device: cpu
data:
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)


- Tensor 저장 및 실행 위치
    - attribute device 설정

In [12]:
# 실행 위치 => CPU/GPU
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
print(DEVICE)

cpu


In [13]:
# real number tensor
data_ts1 = torch.DoubleTensor(data)
data_ts2 = torch.tensor(data, dtype=torch.float64, device=DEVICE)

printInfo(data_ts1, 'data_ts1')
printInfo(data_ts2, 'data_ts2')


[data_ts1]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float64
device: cpu
data:
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)

[data_ts2]
shape: torch.Size([3])
ndim: 1D
dtype: torch.float64
device: cpu
data:
tensor([1.4000, 2.8000, 3.1000], dtype=torch.float64)
