### 넘파이 Chapter 5
- 변경 및 결합 주요 함수
- 내부 조작 함수
- 배열의 padding

In [1]:
import numpy as np

- 변경 및 결합 주요 함수
    - 변형 및 변경 함수

In [2]:
# 배열의 형상 변형하기
x = np.arange(16)
print(x)
print()

x1 = x.reshape(2, 8)
print(x1)
print()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]



In [4]:
try:
    x2 = x.reshape(4, 5)
except Exception as e:
    print(e)

cannot reshape array of size 16 into shape (4,5)


In [5]:
y = x.reshape(2, 2, 4)
print(y)
print()

y1 = x.reshape(4, -1)
print(y1)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
try:
    y2 = x.reshape(2, -1, -1)
except Exception as e:
    print(e)

can only specify one unknown dimension


In [7]:
y2 = x.reshape(2, 2, -1)
y2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [8]:
# 배열의 크기를 늘리기 및 줄이기
a = np.arange(4)
print(a)
print()

print(np.resize(a, 8))
print()

print(np.append(a,a))

[0 1 2 3]

[0 1 2 3 0 1 2 3]

[0 1 2 3 0 1 2 3]


In [10]:
b = np.arange(4)
b.resize((4, 4))
print(b)
print()

c = np.arange(8)
print(c)
print()

c.resize(4, refcheck=False)
print(c)
print()

d = np.arange(16)
print(d)
print()

d.resize(3, 3, refcheck=False)
print(d)
print()

e = np.arange(9)
e.resize(4, 4)
print(e)
print()

print(e.flatten())

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[0 1 2 3 4 5 6 7]

[0 1 2 3]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2 3]
 [4 5 6 7]
 [8 0 0 0]
 [0 0 0 0]]

[0 1 2 3 4 5 6 7 8 0 0 0 0 0 0 0]


In [11]:
# 격자를 사용해서 확장 처리하기
x = np.arange(3)
y = np.arange(4)

x_, y_ = np.meshgrid(x, y)
print(x_)
print()

print(y_)
print()

x_1 = x.reshape(1, -1)
print(np.concatenate([x_1, x_1, x_1, x_1]))
print()

y_1 = y.reshape(-1, 1)
print(np.concatenate([y_1, y_1, y_1, y_1]))

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]

[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]

[[0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]
 [0]
 [1]
 [2]
 [3]]


In [12]:
# 격자 객체를 사용한 확장처리
print(type(np.mgrid))
print()

print(np.mgrid.__class__)
print()

print(np.arange(1, 30, 10))
print()

print(np.arange(1, 5))
print()

print(np.broadcast_arrays(np.arange(10, 30, 10).reshape(2, 1), np.arange(1, 5).reshape(1, 4)))

<class 'numpy.lib._index_tricks_impl.MGridClass'>

<class 'numpy.lib._index_tricks_impl.MGridClass'>

[ 1 11 21]

[1 2 3 4]

(array([[10, 10, 10, 10],
       [20, 20, 20, 20]]), array([[1, 2, 3, 4],
       [1, 2, 3, 4]]))


In [13]:
a, b = np.mgrid[10:30:10, 1:5]

print(a)
print()
print(b)
print()

s1 = slice(10, 30, 10)
s2 = slice(1, 5)
a_, b_ = np.mgrid[s1, s2]

print(a_)
print()
print(b_)
print()

print(type(np.ogrid))
print()

c, d = np.ogrid[10:30:10, 1:5]
print(c)
print()
print(d)
print()

e, f = np.broadcast_arrays(c, d)
print(e)
print()
print(f)

[[10 10 10 10]
 [20 20 20 20]]

[[1 2 3 4]
 [1 2 3 4]]

[[10 10 10 10]
 [20 20 20 20]]

[[1 2 3 4]
 [1 2 3 4]]

<class 'numpy.lib._index_tricks_impl.OGridClass'>

[[10]
 [20]]

[[1 2 3 4]]

[[10 10 10 10]
 [20 20 20 20]]

[[1 2 3 4]
 [1 2 3 4]]


In [14]:
# 특정 조건만 추츨하기
a = np.array([[1, 3], [2, 5], [3, 7]])
print(a)
print()

print(np.compress([0, 1], a))
print(a[[0], [1]])
print(np.compress([0, 1, 1, 0, 0, 0], a))
print()

print(np.compress([0, 1, 0], a, axis=0))
print()

print(np.compress([0, 1], a, axis=1))
print()

cond = np.mod(a, 3)
print(cond)
print()

print(np.extract(cond, a))
print()

cc = np.array([[1, 0], [1, 1,], [0, 1]])
print(np.extract(cc, a))

[[1 3]
 [2 5]
 [3 7]]

[3]
[3]
[3 2]

[[2 5]]

[[3]
 [5]
 [7]]

[[1 0]
 [2 2]
 [0 1]]

[1 2 5 7]

[1 2 5 7]


In [15]:
# 내부의 1인 차원을 없애기
x = np.array([[[0], [1], [2]]])
print(x)
print()
print(x.shape)
print()

print(np.squeeze(x))
print()
print(np.squeeze(x, axis=0))
print()
print(np.squeeze(x, axis=2))
print()

y = np.array([[0], [1]])
print(y.shape)
print(np.squeeze(y, 1))

z = np.array([[0, 2], [1, 3]])
print(np.squeeze(z))
print()

try:
    np.squeeze(z, 1)
except Exception as e:
    print(e)

[[[0]
  [1]
  [2]]]

(1, 3, 1)

[0 1 2]

[[0]
 [1]
 [2]]

[[0 1 2]]

(2, 1)
[0 1]
[[0 2]
 [1 3]]

cannot select an axis to squeeze out which has size not equal to one


- 변경 및 결합의 주요 함수
    - 배열 내의 원소 반복하기

In [16]:
# 원소를 추가해서 배열 확장하기
a = np.linspace(1, 5, 5, dtype=np.int32)
print(a)
print()
print(np.repeat(a, 2))
print()
print(np.repeat(a, [2, 2, 2, 2, 2]))
print()
print(np.repeat(a, [2, 0, 0, 0, 0]))

[1 2 3 4 5]

[1 1 2 2 3 3 4 4 5 5]

[1 1 2 2 3 3 4 4 5 5]

[1 1]


In [17]:
b = np.linspace(1, 4, 4, dtype=np.int32).reshape(2, 2)
print(b)
print()
print(np.repeat(b, 2, axis=0))
print()
print(np.repeat(b, 2, axis=1))
print()
print(np.repeat(b, [2,3], axis=0))
print()
print(np.repeat(b, [2, 3], axis=1))

[[1 2]
 [3 4]]

[[1 2]
 [1 2]
 [3 4]
 [3 4]]

[[1 1 2 2]
 [3 3 4 4]]

[[1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]

[[1 1 2 2 2]
 [3 3 4 4 4]]


In [18]:
# 배열의 크기에 맞춰 늘리기
e = np.arange(4).reshape(2, 2)
print(e)
print()
print(np.tile(e, 2))
print()
print(np.tile(e, [2, 2]))
print()
print(np.tile(e, [2, 2, 2]))

[[0 1]
 [2 3]]

[[0 1 0 1]
 [2 3 2 3]]

[[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]

[[[0 1 0 1]
  [2 3 2 3]
  [0 1 0 1]
  [2 3 2 3]]

 [[0 1 0 1]
  [2 3 2 3]
  [0 1 0 1]
  [2 3 2 3]]]


- 변경 및 결합 주요 함수
    - 배열을 결합하는 함수

In [19]:
# 두 배열을 단순히 결합하기
a = np.linspace(1, 6, 6, dtype=np.int32).reshape(2, 3)
print(a)
print()

b = np.linspace(7, 13, 6, dtype=np.int32).reshape(2, 3)
print(b)
print()

print(np.concatenate([a, b]))
print()
print(np.concatenate([a, b], axis=0))

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 13]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 13]]


In [20]:
c = np.linspace(7, 15, 8, dtype=np.int32).reshape(2, 4)
c

array([[ 7,  8,  9, 10],
       [11, 12, 13, 15]], dtype=int32)

In [21]:
try:
    np.concatenate([a, c], axis=0)
except Exception as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4


In [22]:
np.concatenate([a, b], axis=1)


array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 13]], dtype=int32)

In [23]:
np.concatenate([a,c], axis=1)

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 15]], dtype=int32)

In [24]:
# 배열을 쌓기
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.stack([x, y]))
print()
print(np.stack([x, y], axis=0))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [25]:
z = np.array([7, 8, 9, 10])

try:
    np.stack([x, z], axis=0)
except Exception as e:
    print(e)

all input arrays must have the same shape


In [26]:
print(np.stack([x, y], axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [27]:
try:
    np.stack([x, z], axis=1)
except Exception as e:
    print(e)

all input arrays must have the same shape


In [28]:
np.stack([x, y], axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [29]:
# 축 지정 없이 배열 쌓기
a = np.vstack([x, y])
print(a)
print()

print(np.vstack([a, a]))
print()
print(np.vstack([[a, a]]))

[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [30]:
b = np.hstack([x, y])
print(b)
print()

print(np.hstack([b, b]))
print()

c = b.reshape(1, 6)
print(np.hstack([c, c]))
print()
print(np.row_stack([a, a]))
print()
print(np.column_stack([b, b]))

[1 2 3 4 5 6]

[1 2 3 4 5 6 1 2 3 4 5 6]

[[1 2 3 4 5 6 1 2 3 4 5 6]]

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]]


C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_27292\4080778160.py:11: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  print(np.row_stack([a, a]))


In [32]:
# 축을 확대하기
a

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
np.dstack([a, a])

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]]])

In [34]:
x = np.array([[1], [2], [3]])
x

array([[1],
       [2],
       [3]])

In [35]:
y = np.array([[2], [3], [4]])
y

array([[2],
       [3],
       [4]])

In [36]:
np.dstack([x, y])

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]]])

- 변경 및 결합 주요 함수
    - 배열을 분리하는 함수

In [37]:
# 하나의 배열을 분리하는 함수
a = np.linspace(1, 6, 6, dtype=np.int32).reshape(2, 3)
a


array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [38]:
b = np.vstack([a, a])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [39]:
x, y = np.split(b, [2])
x,y

(array([[1, 2, 3],
        [4, 5, 6]], dtype=int32),
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32))

In [40]:
a, b, c = np.split(b, [1, 3])
a, b, c

(array([[1, 2, 3]], dtype=int32),
 array([[4, 5, 6],
        [1, 2, 3]], dtype=int32),
 array([[4, 5, 6]], dtype=int32))

In [42]:
bb = np.linspace(1, 6, 6, dtype=np.int32).reshape(2, 3)
bb

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [43]:
h1, h2 = np.split(bb, [2], axis=1)
h1, h2

(array([[1, 2],
        [4, 5]], dtype=int32),
 array([[3],
        [6]], dtype=int32))

In [44]:
# 배열을 분리하기
v1 = np.array([[1, 2, 3], [4, 5, 6]])
v2 = np.array([[11, 12, 13], [14, 15, 16]])
v = np.vstack([v1, v2])
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [46]:
x, y = np.vsplit(v, [2])
x, y

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]))

In [47]:
x1, y1, z1 = np.vsplit(v, [1, 3])
x1, y1, z1

(array([[1, 2, 3]]),
 array([[ 4,  5,  6],
        [11, 12, 13]]),
 array([[14, 15, 16]]))

In [48]:
h = np.hstack([v1, v2])
h

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [49]:
x2, y2, z2 = np.hsplit(h, [1, 3])
x2, y2, z2

(array([[1],
        [4]]),
 array([[2, 3],
        [5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]))

In [50]:
# 배열에 축과 형상을 주고 분리하기
a = np.arange(16).reshape(4, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
c = np.array_split(a, (2, ), axis=0)
c

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [52]:
c_ = np.array_split(a, (3, ), axis=0)
c_

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [54]:
d = np.array_split(a, (2, ), axis=1)
d[0], d[1]

(array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]))

- 1-5 배열 쌓기 도우미 객체(여기서부터는 인덱스로)

In [55]:
# 행단위로 처리
a = np.arange(6).reshape(2, 3)
b = np.arange(3)

print(np.r_)
print(type(np.r_))

<class 'numpy.lib._index_tricks_impl.RClass'>


In [56]:
try:
    np.r_[a, b]
except Exception as e:
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


In [57]:
c = np.random.randn(2, 3)
np.r_[a,c]

array([[ 0.        ,  1.        ,  2.        ],
       [ 3.        ,  4.        ,  5.        ],
       [-0.74442796,  0.07534706, -0.6698011 ],
       [-0.56309275, -0.97141445, -1.13528841]])

In [58]:
# 열 단위로 처리
print(np.c_)
print(type(np.c_))
print(np.c_[a, c])

<class 'numpy.lib._index_tricks_impl.CClass'>
[[ 0.          1.          2.         -0.74442796  0.07534706 -0.6698011 ]
 [ 3.          4.          5.         -0.56309275 -0.97141445 -1.13528841]]


In [59]:
# 행과 열을 조합해서 처리
d = np.arange(4)
np.c_[np.r_[a,c], d]

array([[ 0.        ,  1.        ,  2.        ,  0.        ],
       [ 3.        ,  4.        ,  5.        ,  1.        ],
       [-0.74442796,  0.07534706, -0.6698011 ,  2.        ],
       [-0.56309275, -0.97141445, -1.13528841,  3.        ]])

- 2-1 정렬함수

In [60]:
# 배열을 정렬하기
a = np.linspace(1, 6, 6, dtype=np.int32)
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [61]:
np.random.shuffle(a)
a

array([5, 4, 6, 3, 1, 2], dtype=int32)

In [62]:
b = np.sort(a)
b

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [63]:
a

array([5, 4, 6, 3, 1, 2], dtype=int32)

In [65]:
a.sort()
a

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [66]:
bb = np.linspace(1, 6, 6, dtype=np.int32)
bb

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [67]:
np.random.shuffle(bb)
bb

array([2, 4, 5, 6, 3, 1], dtype=int32)

In [68]:
c = np.argsort(bb)
c

array([5, 0, 4, 1, 2, 3])

In [69]:
bb[c[0]], bb[c[1]]

(np.int32(1), np.int32(2))

In [70]:
d = np.random.randn(3, 4)
d

array([[-1.53508902,  0.99478287, -0.51842608, -0.82873587],
       [ 2.4181445 , -1.18440018, -1.04385684,  0.83934376],
       [-0.79846766,  0.2007911 ,  0.32503772,  1.37778567]])

In [71]:
np.sort(d, axis=1)

array([[-1.53508902, -0.82873587, -0.51842608,  0.99478287],
       [-1.18440018, -1.04385684,  0.83934376,  2.4181445 ],
       [-0.79846766,  0.2007911 ,  0.32503772,  1.37778567]])

In [72]:
np.sort(d, axis=0)

array([[-1.53508902, -1.18440018, -1.04385684, -0.82873587],
       [-0.79846766,  0.2007911 , -0.51842608,  0.83934376],
       [ 2.4181445 ,  0.99478287,  0.32503772,  1.37778567]])

In [73]:
# 다양한 배열을 정렬하기
v1 = np.array(['문', '홍', '강'])
np.sort(v1)

array(['강', '문', '홍'], dtype='<U1')

In [74]:
v2 = np.array(['소을', '가고', '도나'])
np.sort(v2)

array(['가고', '도나', '소을'], dtype='<U2')

In [75]:
res = []
for f,l in zip(v1, v2):
    res.append(l + f)
res

['소을문', '가고홍', '도나강']

In [76]:
v3 = np.array(res)
v3

array(['소을문', '가고홍', '도나강'], dtype='<U3')

In [77]:
np.sort(v3)

array(['가고홍', '도나강', '소을문'], dtype='<U3')

In [78]:
np.lexsort([v1, v2])

array([1, 2, 0])

- 2-2 다차원 배열 변환 및 변경하기

In [79]:
# 배열 클래스 변경하기
m = np.matrix([1, 2, 3, 4])
m

matrix([[1, 2, 3, 4]])

In [80]:
type(m)

numpy.matrix

In [81]:
a = np.asarray(m)
print(a)
print(type(a))

[[1 2 3 4]]
<class 'numpy.ndarray'>


In [82]:
m1 = np.asmatrix(a)
m1

matrix([[1, 2, 3, 4]])

In [83]:
b = np.array([3, 4, 5, 6])
b.dtype

dtype('int64')

In [84]:
c = np.asarray(d, dtype='float')
c

array([[-1.53508902,  0.99478287, -0.51842608, -0.82873587],
       [ 2.4181445 , -1.18440018, -1.04385684,  0.83934376],
       [-0.79846766,  0.2007911 ,  0.32503772,  1.37778567]])

In [85]:
c.dtype

dtype('float64')

In [86]:
bb = np.linspace(1, 6, 6, dtype=np.int32)
bb

array([1, 2, 3, 4, 5, 6], dtype=int32)

In [88]:
mm = np.asmatrix(bb)
mm

matrix([[1, 2, 3, 4, 5, 6]], dtype=int32)

In [89]:
# 배열 원소의 값 변경
o =np.ones(10)
o

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [92]:
o.fill(100)
o

array([100., 100., 100., 100., 100., 100., 100., 100., 100., 100.])

In [93]:
a = np.full(o.shape, 99.)
a

array([99., 99., 99., 99., 99., 99., 99., 99., 99., 99.])

In [94]:
# 배열 원소에 대한 위치 변경하기
array = np.arange(4). reshape((2, 2))
array

array([[0, 1],
       [2, 3]])

In [95]:
np.fliplr(array)

array([[1, 0],
       [3, 2]])

In [97]:
np.flipud(array)

array([[2, 3],
       [0, 1]])

In [98]:
array1 = np.arange(8).reshape((2, 2, 2))
array1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [99]:
np.fliplr(array1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [100]:
np.flipud(array1)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [101]:
# 배열 원서에 회전시키기
m = np.array([[1, 2], [3, 4]], int)
m

array([[1, 2],
       [3, 4]])

In [102]:
np.rot90(m)

array([[2, 4],
       [1, 3]])

In [103]:
np.rot90(m,2)

array([[4, 3],
       [2, 1]])

In [104]:
np.rot90(m,3)

array([[3, 1],
       [4, 2]])

In [106]:
np.rot90(m,4)

array([[1, 2],
       [3, 4]])

In [107]:
l = np.arange(1, 11)
np.roll(l, l)

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [108]:
ll = np.reshape(l, (2, 5))
ll

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [109]:
s = np.roll(ll, l)
s

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [110]:
s.flatten()

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [111]:
np.roll(ll, 2)

array([[ 9, 10,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [112]:
np.roll(ll, 2).flatten()

array([ 9, 10,  1,  2,  3,  4,  5,  6,  7,  8])

In [114]:
np.roll(ll, l, axis=0)

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [115]:
np.roll(ll, 1, axis=0).flatten()

array([ 6,  7,  8,  9, 10,  1,  2,  3,  4,  5])

In [116]:
np.roll(ll, l, axis=1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [117]:
np.roll(ll, l, axis=1).flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- 2-3 배열 내의 원소 점검하기

In [118]:
# 숫자 값 체크
m = np.random.randn(3, 5)
m

array([[-1.00826453,  0.10208903, -1.03041866,  0.93275856, -0.86921282],
       [-1.8681409 ,  0.70886101, -0.65933451, -2.32715473,  0.36555735],
       [-0.48419165, -1.97736726, -0.47517129, -0.13063765, -0.08685165]])

In [119]:
np.isreal(m)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [121]:
np.isinf(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [122]:
np.isnan(m)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [123]:
x = np.array([1, 2+3j, 3, 4], dtype=np.complex64)
np.iscomplex(x)

array([False,  True, False, False])

In [124]:
x.real

array([1., 2., 3., 4.], dtype=float32)

In [125]:
x.imag

array([0., 3., 0., 0.], dtype=float32)

In [126]:
# 제로 값 체크
a = np.zeros((3, 5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [127]:
np.nonzero(a)

(array([], dtype=int64), array([], dtype=int64))

In [128]:
a[2, 2] = 100
a[2, 3] = 99
np.nonzero(a)

(array([2, 2]), array([2, 3]))

- 3-1 패딩 되는 원소가 상수 처리

In [129]:
x = np.arange(1, 5).reshape(2, 2)
x

array([[1, 2],
       [3, 4]])

In [130]:
z = np.zeros((3, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [131]:
z[:2, :2] = x
x

array([[1, 2],
       [3, 4]])

In [132]:
np.pad(x, 0, "constant")

array([[1, 2],
       [3, 4]])

In [133]:
np.pad(x, (0, 1), "constant")

array([[1, 2, 0],
       [3, 4, 0],
       [0, 0, 0]])

In [134]:
np.pad(x, (1, 0), "constant")

array([[0, 0, 0],
       [0, 1, 2],
       [0, 3, 4]])

In [135]:
np.pad(x, (1, 1), "constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [136]:
np.pad(x, 1, "constant")

array([[0, 0, 0, 0],
       [0, 1, 2, 0],
       [0, 3, 4, 0],
       [0, 0, 0, 0]])

In [137]:
np.pad(x, (3, 3), "constant")

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2, 0, 0, 0],
       [0, 0, 0, 3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [138]:
np.pad(x, (3, 0), "constant")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 1, 2],
       [0, 0, 0, 3, 4]])

In [139]:
np.pad(x, (0, 3), "constant")

array([[1, 2, 0, 0, 0],
       [3, 4, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

- 3-2 기존 배열의 원소로 패딩 하기

In [140]:
# 기존의 값으로 패딩하기
x = np.arange(1, 5).reshape(2, 2)
x

array([[1, 2],
       [3, 4]])

In [141]:
np.pad(x, (0, 1), "edge")

array([[1, 2, 2],
       [3, 4, 4],
       [3, 4, 4]])

In [142]:
np.pad(x, (1, 0), "edge")

array([[1, 1, 2],
       [1, 1, 2],
       [3, 3, 4]])

In [143]:
np.pad(x, (1, 1), "edge")

array([[1, 1, 2, 2],
       [1, 1, 2, 2],
       [3, 3, 4, 4],
       [3, 3, 4, 4]])

In [144]:
np.pad(x, (3, 3), 'edge')

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4],
       [3, 3, 3, 3, 4, 4, 4, 4]])

In [145]:
np.pad(x, (3, 3), 'maximum')

array([[4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [4, 4, 4, 3, 4, 4, 4, 4]])

In [146]:
np.pad(x, (3, 3), 'minimum')

array([[1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [3, 3, 3, 3, 4, 3, 3, 3],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1],
       [1, 1, 1, 1, 2, 1, 1, 1]])

- 3-3 배열 확장을 특정 계산 결과로 하기

In [147]:
x = np.arange(1, 5).reshape(2, 2)
x

array([[1, 2],
       [3, 4]])

In [148]:
np.pad(x, (0, 1), 'mean')

array([[1, 2, 2],
       [3, 4, 4],
       [2, 3, 2]])

In [149]:
np.pad(x, (1, 0), 'mean')

array([[2, 2, 3],
       [2, 1, 2],
       [4, 3, 4]])

In [150]:
np.pad(x, (1, 1), 'mean')

array([[2, 2, 3, 2],
       [2, 1, 2, 2],
       [4, 3, 4, 4],
       [2, 2, 3, 2]])

In [151]:
np.pad(x, (3, 3), 'mean')

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])

In [152]:
np.pad(x, (3, 3), 'median')

array([[2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 1, 2, 2, 2, 2],
       [4, 4, 4, 3, 4, 4, 4, 4],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2],
       [2, 2, 2, 2, 3, 2, 2, 2]])