### 넘파이 Chapter 6
- dtype으로 자료형 객체 사용하기
- 날짜 자료형
- 문자 자료형

In [1]:
import numpy as np

- 1-1 np.dtype 클래스 이해하기

In [2]:
# dtype 클래스 알아보기
np.dtype

numpy.dtype

In [3]:
d = np.dtype(np.int32)
d

dtype('int32')

In [4]:
a = np.array([1, 2, 3, 4], dtype=d)
a

array([1, 2, 3, 4], dtype=int32)

In [5]:
a.dtype

dtype('int32')

In [8]:
# 자료형 클래스 알아보기
np.int_

numpy.int64

In [9]:
np.int_.mro()

[numpy.int64,
 numpy.signedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [10]:
issubclass(np.int32, np.signedinteger)

True

In [11]:
issubclass(np.integer, np.number)

True

In [12]:
issubclass(np.number, np.generic)

True

In [13]:
p_i = int(100)
p_i

100

In [14]:
n_i = np.int32(100)
n_i

np.int32(100)

In [15]:
p_i + n_i

np.int32(200)

In [16]:
a = np.array([1, 2, 3, 4, 5], dtype=np.int64)
a.strides, a.itemsize

((8,), 8)

In [17]:
a.data.nbytes

40

In [18]:
b = np.array([1, 2, 3, 4, 5], dtype=np.int64)
b.strides, b.itemsize

((8,), 8)

In [19]:
b.data.nbytes

40

- 1-2 자료형 클래스 구조 이해하기

In [20]:
# 자료형 클래스 구조 알아보기
np.generic

numpy.generic

In [21]:
np.generic.__base__

object

In [23]:
np.object_

numpy.object_

In [24]:
np.object_.__base__

numpy.generic

In [25]:
s = np.dtype(str)
s

dtype('<U')

In [26]:
s.name

'str'

In [27]:
a = np.array(['a', 'b'], dtype=s)
a.dtype

dtype('<U1')

In [28]:
a[0] = 'cde'
a.dtype

dtype('<U1')

In [29]:
a

array(['c', 'b'], dtype='<U1')

In [30]:
b = np.array([b'a', b'b'])
b.dtype

dtype('S1')

In [31]:
np.character

numpy.character

In [32]:
np.character.__base__

numpy.flexible

In [33]:
try:
    c =np.character('a')
except Exception as e:
    print(e)

cannot create 'numpy.character' instances


In [34]:
dc = np.dtype(np.character)
da =np.array(['a', 'b'], dtype=dc)
da

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_12144\2335448807.py:1: DeprecationWarning: Converting `np.character` to a dtype is deprecated. The current result is `np.dtype(np.str_)` which is not strictly correct. Note that `np.character` is generally deprecated and 'S1' should be used.
  dc = np.dtype(np.character)


array([b'a', b'b'], dtype='|S1')

In [35]:
import pprint

In [36]:
pprint.pprint(np.int32.mro())

[<class 'numpy.int32'>,
 <class 'numpy.signedinteger'>,
 <class 'numpy.integer'>,
 <class 'numpy.number'>,
 <class 'numpy.generic'>,
 <class 'object'>]


In [37]:
pprint.pprint(np.int32.mro())

[<class 'numpy.int32'>,
 <class 'numpy.signedinteger'>,
 <class 'numpy.integer'>,
 <class 'numpy.number'>,
 <class 'numpy.generic'>,
 <class 'object'>]


In [38]:
pprint.pprint(np.float64.mro())

[<class 'numpy.float64'>,
 <class 'numpy.floating'>,
 <class 'numpy.inexact'>,
 <class 'numpy.number'>,
 <class 'numpy.generic'>,
 <class 'float'>,
 <class 'object'>]


In [39]:
pprint.pprint(np.complex64.mro())

[<class 'numpy.complex64'>,
 <class 'numpy.complexfloating'>,
 <class 'numpy.inexact'>,
 <class 'numpy.number'>,
 <class 'numpy.generic'>,
 <class 'object'>]


- 2-1 날짜처리

In [40]:
#  날짜 클래스 알아보기
np.datetime64

numpy.datetime64

In [42]:
print(np.datetime64)

<class 'numpy.datetime64'>


In [44]:
count = 0
for i in dir(np.datetime64):
    if not i.startswith("_"):
        count += 1
        print(i, end=' ')
        if count%5 == 0:
            print()

T all any argmax argmin 
argsort astype base byteswap choose 
clip compress conj conjugate copy 
cumprod cumsum data diagonal dtype 
dump dumps fill flags flat 
flatten getfield imag item itemset 
itemsize max mean min nbytes 
ndim newbyteorder nonzero prod ptp 
put ravel real repeat reshape 
resize round searchsorted setfield setflags 
shape size sort squeeze std 
strides sum swapaxes take tobytes 
tofile tolist tostring trace transpose 
var view 

In [45]:
y = np.datetime64('2018')
y, y.dtype

(np.datetime64('2018'), dtype('<M8[Y]'))

In [46]:
ym = np.datetime64('2018-11')
ym, ym.dtype

(np.datetime64('2018-11'), dtype('<M8[M]'))

In [47]:
ymd = np.datetime64('2018-11-15')
ymd, ymd.dtype

(np.datetime64('2018-11-15'), dtype('<M8[D]'))

In [49]:
a = np.array(['2018-11-15', '2018-12-15', '2010-01-15'], dtype = np.datetime64)
a

array(['2018-11-15', '2018-12-15', '2010-01-15'], dtype='datetime64[D]')

In [50]:
np.timedelta64

numpy.timedelta64

In [51]:
delta = np.datetime64('2018-11-15') - np.datetime64('2016-11-15')
delta, delta.dtype

(np.timedelta64(730,'D'), dtype('<m8[D]'))

In [52]:
print(delta)

730 days


In [55]:
a = np.arange('2019-02', '2019-03', dtype='datetime64[D]')
a

array(['2019-02-01', '2019-02-02', '2019-02-03', '2019-02-04',
       '2019-02-05', '2019-02-06', '2019-02-07', '2019-02-08',
       '2019-02-09', '2019-02-10', '2019-02-11', '2019-02-12',
       '2019-02-13', '2019-02-14', '2019-02-15', '2019-02-16',
       '2019-02-17', '2019-02-18', '2019-02-19', '2019-02-20',
       '2019-02-21', '2019-02-22', '2019-02-23', '2019-02-24',
       '2019-02-25', '2019-02-26', '2019-02-27', '2019-02-28'],
      dtype='datetime64[D]')

- 2-2 시간에 대한 처리

In [56]:
# 시간 처리 알아보기
h = np.datetime64('2018-12-01T01')
h

np.datetime64('2018-12-01T01','h')

In [57]:
h.dtype

dtype('<M8[h]')

In [58]:
print(h.dtype)

datetime64[h]


In [59]:
m = np.datetime64('2018-12-01T01:01')
m

np.datetime64('2018-12-01T01:01')

In [60]:
m.dtype

dtype('<M8[m]')

In [61]:
print(m.dtype)

datetime64[m]


In [62]:
s = np.datetime64('2018-12-01T01:01:01')
s

np.datetime64('2018-12-01T01:01:01')

In [63]:
print(s.dtype)

datetime64[s]


In [64]:
s1 = np.datetime64('2018-12-01T01:31:01')
s2 = np.datetime64('2018-12-01T01:01:01')
s3 = s1 - s2
print(s3)
print(s3.dtype)

1800 seconds
timedelta64[s]


In [65]:
s2+s3

np.datetime64('2018-12-01T01:31:01')

In [66]:
np.datetime64('2018-12-01T01:01:01') + np.timedelta64(1800, 's')

np.datetime64('2018-12-01T01:31:01')

In [67]:
np.datetime64('2019') + np.timedelta64(20, 'D')

np.datetime64('2019-01-21')

In [75]:
# np.datetime64('2019') + np.datetime64(20, 'h')

- 2-3 비즈니스 일자 처리

In [76]:
# 열업일 처리 알아보기
start = np.datetime64('2018-11-01')
end = np.datetime64('2018-11-30')
np.busday_count(start, end)

np.int64(21)

In [77]:
np.busday_offset('2018-11-15', 1)

np.datetime64('2018-11-16')

In [78]:
np.busday_offset('2018-11-15', 2)

np.datetime64('2018-11-19')

In [79]:
np.busday_offset('2018-11-15', 5)

np.datetime64('2018-11-22')

In [80]:
print(np.busday_offset('2019-09-21', 0, roll='forward'))
print(np.busday_offset('2019-09-21', 1, roll='forward'))
print(np.busday_offset('2019-09-21', 0, roll='backward'))
print(np.busday_offset('2019-09-21', 1, roll='backward'))

2019-09-23
2019-09-24
2019-09-20
2019-09-23


In [81]:
np.busday_offset('2019-09-19', 0, roll='forward', weekmask='Sun')


np.datetime64('2019-09-22')

In [83]:
np.busday_offset('2019-09-19', 1, roll='forward', weekmask='Sun')

np.datetime64('2019-09-29')

In [84]:
np.busday_offset('2019-09-19', 0, roll='forward', weekmask='Mon')

np.datetime64('2019-09-23')

In [85]:
np.is_busday('2018-11-16')

np.True_

In [86]:
np.is_busday('2018-11-17')

np.False_

In [87]:
np.is_busday(start) , np.is_busday(end) 

(np.True_, np.True_)

In [88]:
a = np.busday_count(np.datetime64('2019-07-11'), np.datetime64('2019-07-18'))
b = np.busday_count(np.datetime64('2019-07-18'), np.datetime64('2019-07-11'))

a, b

(np.int64(5), np.int64(-5))

In [89]:

np.datetime64('2019-07-11') + np.timedelta64(a+2,'D')

np.datetime64('2019-07-18')

In [90]:
bdd = np.busdaycalendar(holidays=['2019-01-01','2019-09-23'])
bdd.holidays

array(['2019-01-01', '2019-09-23'], dtype='datetime64[D]')

In [91]:

bdd.weekmask

array([ True,  True,  True,  True,  True, False, False])

In [92]:
bdc = np.busdaycalendar(holidays=['2019-01-01','2019-09-23'], weekmask='0111110')

bdc.weekmask

array([False,  True,  True,  True,  True,  True, False])

- 3-1 넘파이 모듈 문자열 알아보기

In [97]:
# 문자형 자료 알아보기

np.str_

numpy.str_

In [102]:
np.str_ is str

False

In [103]:
np.str_ is bytes

False

In [104]:
s = np.array([['a', 'b'],['c', 'd']], dtype='S')
s

array([[b'a', b'b'],
       [b'c', b'd']], dtype='|S1')

In [105]:
s[0,0]

np.bytes_(b'a')

In [106]:

type(s[0,0])

numpy.bytes_

In [107]:
s[0,0].dtype

dtype('S1')

In [108]:
u1 = np.array([['a', 'b'],['c', 'd']])
u1

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [109]:
u2 = np.array([['a', 'b'],['c', 'd']], dtype='U')
u2

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [110]:
ss = np.dtype(np.str_)
b = np.array([['a', 'b'],['c', 'd']], dtype=ss)
b

array([['a', 'b'],
       ['c', 'd']], dtype='<U1')

In [111]:
print(b.dtype)

<U1


In [113]:
c = np.chararray(3,3)
c

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_12144\2865980292.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  c = np.chararray(3,3)


chararray(['', '', b'\x00\x00\x10'], dtype='|S3')

In [114]:
c.dtype

dtype('S3')

In [115]:
c[0] = 'abc'
c

chararray([b'abc', '', b'\x00\x00\x10'], dtype='|S3')

- 3-2 파이썬 문자열 연계 알아보기

In [117]:
# 파이썬 문자열 처리하기
a = np.array(['abc', '12345'], dtype=object)
a

array(['abc', '12345'], dtype=object)

In [118]:
type(a[0])

str

In [119]:
b = np.array([b'abc', b'12345'], dtype=object)
b

array([b'abc', b'12345'], dtype=object)

In [120]:
type(b[0])

bytes

In [121]:
d = np.array(range(10), dtype=str).reshape(2,5)
d

array([['0', '1', '2', '3', '4'],
       ['5', '6', '7', '8', '9']], dtype='<U1')

In [122]:
d[0, 0] = 'Hello'
d

array([['H', '1', '2', '3', '4'],
       ['5', '6', '7', '8', '9']], dtype='<U1')

In [123]:
d5 = np.array(range(10), dtype='S5').reshape(2,5)
d5

array([[b'0', b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8', b'9']], dtype='|S5')

In [125]:
d5[0, 0] = 'Hello'
d5

array([[b'Hello', b'1', b'2', b'3', b'4'],
       [b'5', b'6', b'7', b'8', b'9']], dtype='|S5')

In [126]:
d16 = np.array([["a","b"],["c","d"]],dtype=np.dtype('U16'))
d16

array([['a', 'b'],
       ['c', 'd']], dtype='<U16')

In [127]:
d16[0,0] = "우주론과 빅뱅등 물리학이론"
d16

array([['우주론과 빅뱅등 물리학이론', 'b'],
       ['c', 'd']], dtype='<U16')