### 책의 넘파이 파트를 해볼겨..
- 개인적인 공부
- p.14

In [1]:
import numpy as np

In [2]:
# 넘파이 ndarray 개요
# 생성된 ndarray 배열의 shape 변수는 ndarray의 크기 즉, 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음.

array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 shape: ', array1.shape)

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print(f'array2 type: {type(array2)}')
print(f"array2 shape: {array2.shape}")

array3 = np.array([[1, 2, 3]])
print(f"array3 type: {type(array3)}")
print(f"array3 shape: {array3.shape}")

array1 type:  <class 'numpy.ndarray'>
array1 shape:  (3,)
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 shape: (1, 3)


In [3]:
# 차원 확인하기
print(f"array1: {array1.ndim}D, array2: {array2.ndim}D, array3: {array3.ndim}D")

array1: 1D, array2: 2D, array3: 2D


In [4]:
# ndarray의 데이터 타입

list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

# 모두 같은 데이터 타입으로 변환됨.

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int64')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int64')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int64
[1 2 3] int64


In [7]:
# ndarray를 편하게 생성하기 - arange, zeros, ones
# 배열을 0이나 1로 채워주는 매서드. arange는 range함수와 유사하고 ndaarry의 데이터 값으로 변환

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
# ndarray의 차원과 크기를 변경하는 reshape()
# reshape() 메서드는 ndarray를 특정 타원 및 크기로 변환

array1 = np.arange(10)
print('array1:', array1, sep='\n')

array2 = array1.reshape(2, 5)
print('array2:', array2, sep='\n')

array3 = array1.reshape(5, 2)
print('array3:', array3, sep='\n')

# 당연하지만 지정한 사이즈로 변경이 불가능하면 오류 발생
# array1.shape(4, 3)은 오류남

array1:
[0 1 2 3 4 5 6 7 8 9]
array2:
[[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(f"array2 shape: {array2.shape}")

array3 = array1.reshape(5, -1)
print(f'array3 shape: {array3.shape}')

# array4 = array.reshape(-1, 4) 에러 발생

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [11]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d:', array3d, sep='\n')

# 3D to 2D
array5 = array3d.reshape(-1, 1)
print('array5:', array5.tolist(), sep='\n')
print('array5 shape:', array5.shape)

# 1D to 2D
array6 = array1.reshape(-1, 1)
print('array6:', array6.tolist(), sep='\n')
print('array6 shape: ', array6.shape)

array3d:
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
array5:
[[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
[[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


In [12]:
# 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

# 단일 값 추출
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(1, 10)
print('array1: ', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int32'>


In [13]:
print('맨 뒤의 값: ', array1[-1], '맨 뒤에서 두 번째 값: ', array1[-2])

맨 뒤의 값:  9 맨 뒤에서 두 번째 값:  8


In [14]:
array1[0] = 9
array1[8] = 0
print('array1: ', array1)

array1:  [9 2 3 4 5 6 7 8 0]


In [16]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index value: ', array2d[0, 0])
print('(roe=0, col=1) index value: ', array2d[0, 1])
print('(row=1, col=0) index value: ', array2d[1, 0])
print('(row=2, col=2) index value: ', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index value:  1
(roe=0, col=1) index value:  2
(row=1, col=0) index value:  4
(row=2, col=2) index value:  9


In [17]:
# 슬라이싱
array1 = np.arange(1, 10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [18]:
array1 = np.arange(1, 10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [19]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print('array2d:', array2d, sep='\n')

print('array2d[0:2, 0:2]', array2d[0:2, 0:2], sep='\n')
print('array2d[1:3, 0:3]', array2d[1:3, 0:3], sep='\n')
print('array2d[1:3, :]', array2d[1:3, :],sep='\n')

array2d:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]
[[1 2]
 [4 5]]
array2d[1:3, 0:3]
[[4 5 6]
 [7 8 9]]
array2d[1:3, :]
[[4 5 6]
 [7 8 9]]


In [20]:
print(array2d[0])
print(array2d[1])
print(f"array2d[0] shape: {array2d[0].shape}, array2d[1] shape: {array2d[1].shape}")

[1 2 3]
[4 5 6]
array2d[0] shape: (3,), array2d[1] shape: (3,)


In [21]:
# 팬시 인덱싱
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print(f'array2d[[0, 1], 2] => {array3.tolist()}')

array4 = array2d[[0, 1]]
print(f"array2d[[0, 1]] => {array4.tolist()}")

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


In [22]:
# 불린 인덱싱
array1d = np.arange(1, 10)

# [] 안에 array1d > 5 boolean indexing을 적용
array3 = array1d[array1d > 5]
print(f"array1d > 5 Boolean Indexing Result: {array3}")

array1d > 5 Boolean Indexing Result: [6 7 8 9]


In [23]:
# 행렬의 정렬 - sort()와 argsort()

# 행렬 정렬
org_array = np.array([3, 1, 9, 5])
print(f"origin array: {org_array}")

# sorting to np.sort()
sort_array1 = np.sort(org_array)
print(f"np.sort() array: {sort_array1}")
print(f"after np.sort() origin_array: {org_array}")

# sorting to ndarray.sort()
sort_array2 = org_array.sort()
print(f"ndarray.sort() array: {sort_array2}")
print(f"after ndarray.sort() array: {org_array}")

origin array: [3 1 9 5]
np.sort() array: [1 3 5 9]
after np.sort() origin_array: [3 1 9 5]
ndarray.sort() array: None
after ndarray.sort() array: [1 3 5 9]


In [24]:
sort_array1_desc = np.sort(org_array)[::-1]
print(f"desc array: {sort_array1_desc}")

desc array: [9 5 3 1]


In [26]:
array2d = np.array([[8, 12], [7, 1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print(f"sort(axis=0) array:\n{sort_array2d_axis0}")

sort_array2d_axis1 = np.sort(array2d, axis=1)
print(f"sort(axis=1) array:\n{sort_array2d_axis1}")

sort(axis=0) array:
[[ 7  1]
 [ 8 12]]
sort(axis=1) array:
[[ 8 12]
 [ 1  7]]


In [28]:
# 정렬된 핼열의 인덱스 반환하기
org_array = np.array([3, 1, 9, 5])
sort_indices =np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


In [29]:
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬의 내림차순 정렬 시 원본 행렬의 인덱스: ', sort_indices_desc)

행렬의 내림차순 정렬 시 원본 행렬의 인덱스:  [2 3 0 1]


In [30]:
name_array = np.array(['Jone', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(f"성적 오름차순 정렬 시 score_array 인덱스: {sort_indices_asc}")
print(f"성적 오름차순 정렬 시 name_array 인덱스: {name_array[sort_indices_asc]}")

성적 오름차순 정렬 시 score_array 인덱스: [0 2 4 1 3]
성적 오름차순 정렬 시 name_array 인덱스: ['Jone' 'Sarah' 'Samuel' 'Mike' 'Kate']


In [31]:
# 선형대수 연산 - 행렬의 내적과 전치 행렬 구하기

# 행렬 내적(내적 곱)
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
dot_product = np.dot(A, B)

print('행렬 내적 결과:', dot_product, sep='\n')

행렬 내적 결과:
[[ 58  64]
 [139 154]]


In [32]:
# 전치 행렬
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:', transpose_mat, sep='\n')

A의 전치 행렬:
[[1 3]
 [2 4]]
