### 책의 넘파이 파트를 해볼겨..
- 개인적인 공부
- p.14

In [1]:
import numpy as np

In [2]:
# 넘파이 ndarray 개요
# 생성된 ndarray 배열의 shape 변수는 ndarray의 크기 즉, 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음.

array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 shape: ', array1.shape)

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print(f'array2 type: {type(array2)}')
print(f"array2 shape: {array2.shape}")

array3 = np.array([[1, 2, 3]])
print(f"array3 type: {type(array3)}")
print(f"array3 shape: {array3.shape}")

array1 type:  <class 'numpy.ndarray'>
array1 shape:  (3,)
array2 type: <class 'numpy.ndarray'>
array2 shape: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 shape: (1, 3)


In [3]:
# 차원 확인하기
print(f"array1: {array1.ndim}D, array2: {array2.ndim}D, array3: {array3.ndim}D")

array1: 1D, array2: 2D, array3: 2D


In [4]:
# ndarray의 데이터 타입

list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

# 모두 같은 데이터 타입으로 변환됨.

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int64')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int64')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int64
[1 2 3] int64


In [7]:
# ndarray를 편하게 생성하기 - arange, zeros, ones
# 배열을 0이나 1로 채워주는 매서드. arange는 range함수와 유사하고 ndaarry의 데이터 값으로 변환

sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [8]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [10]:
# ndarray의 차원과 크기를 변경하는 reshape()
# reshape() 메서드는 ndarray를 특정 타원 및 크기로 변환

array1 = np.arange(10)
print('array1:', array1, sep='\n')

array2 = array1.reshape(2, 5)
print('array2:', array2, sep='\n')

array3 = array1.reshape(5, 2)
print('array3:', array3, sep='\n')

# 당연하지만 지정한 사이즈로 변경이 불가능하면 오류 발생
# array1.shape(4, 3)은 오류남

array1:
[0 1 2 3 4 5 6 7 8 9]
array2:
[[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [11]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(f"array2 shape: {array2.shape}")

array3 = array1.reshape(5, -1)
print(f'array3 shape: {array3.shape}')

# array4 = array.reshape(-1, 4) 에러 발생

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d', array3d, sep='\n')

# 3D to 2D
array5 = array3d.reshape(-1, 1)
