### image drawing
- 이미지 객체 ndarray 필요

In [1]:
import cv2
import numpy as np

In [2]:
PATH = '../image/'

In [36]:
img = PATH+'face.jpg'
bg_data = np.full((500, 500, 3), 255)

cv2.imwrite(PATH+'white_background.jpg', bg_data)

True

In [9]:
print(bg_data)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [34]:
w_bg = cv2.imread('../image/white_background.jpg')
b_bg = cv2.imread('../image/black_backgroung.jpg')

w_bg.shape, w_bg.size, w_bg.ndim

((500, 500, 3), 750000, 3)

In [24]:
# draw line
cv2.line(w_bg, (50, 50), (250, 250), 0)
cv2.line(w_bg, (100, 50), (350, 250), (0, 255, 0), 4)
cv2.line(w_bg, (50, 40), (30, 100), (0, 122.5, 255), 5)
cv2.line(w_bg, (450, 0), (0, 450), (255, 255, 0), 3)

cv2.imshow('draw line', w_bg)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [35]:
# draw square
cv2.rectangle(w_bg, (50, 50), (255, 250), 0, 2)
cv2.rectangle(w_bg, (100, 50), (200, 300), (0, 122.5, 255), 6)
cv2.rectangle(w_bg, (400, 450), (450, 200), (122.5, 0, 122.5), 1)
cv2.rectangle(w_bg, (500, 30), (200, 450), (100, 50, 200), -1)   # 선 두께를 -1를 주면 내부를 채움

cv2.imshow('draw square', w_bg)

cv2.waitKey(0)
cv2.destroyAllWindows()