### 언어 분류 모델 만들기
- datasets: train, test csv
- feature: all columns
- label: en, fr, id, tl
-
- learning method: supervised learning, classification
- learning algorithm: decisontree? support vactor machine? undetermined
- encoding: true
    - encoding method: label incoding

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
# datasets
train_en_df = pd.read_csv('../data/Language/train_en_df.csv', encoding='utf-8')
train_fr_df = pd.read_csv('../data/Language/train_fr_df.csv', encoding='utf-8')
train_id_df = pd.read_csv('../data/Language/train_id_df.csv', encoding='utf-8')
train_tl_df = pd.read_csv('../data/Language/train_tl_df.csv', encoding='utf-8')

test_en_df = pd.read_csv('../data/Language/test_en_df.csv', encoding='utf-8')
test_fr_df = pd.read_csv('../data/Language/test_fr_df.csv', encoding='utf-8')
test_id_df = pd.read_csv('../data/Language/test_id_df.csv', encoding='utf-8')
test_tl_df = pd.read_csv('../data/Language/test_tl_df.csv', encoding='utf-8')

In [42]:
# datasets
train_en_df2 = pd.read_csv('../data/Language/train_en_df2.csv', encoding='utf-8')
train_fr_df2 = pd.read_csv('../data/Language/train_fr_df2.csv', encoding='utf-8')
train_id_df2 = pd.read_csv('../data/Language/train_id_df2.csv', encoding='utf-8')
train_tl_df2 = pd.read_csv('../data/Language/train_tl_df2.csv', encoding='utf-8')

test_en_df2 = pd.read_csv('../data/Language/test_en_df2.csv', encoding='utf-8')
test_fr_df2 = pd.read_csv('../data/Language/test_fr_df2.csv', encoding='utf-8')
test_id_df2 = pd.read_csv('../data/Language/test_id_df2.csv', encoding='utf-8')
test_tl_df2 = pd.read_csv('../data/Language/test_tl_df2.csv', encoding='utf-8')

In [43]:
train_df = pd.concat([train_en_df, train_fr_df, train_id_df, train_tl_df], axis=1)
test_df = pd.concat([test_en_df, test_fr_df, test_id_df, test_tl_df], axis=1)
label_sr = pd.Series(['en', 'fr', 'id', 'tl'])

print(f"train: {train_df.shape}, {train_df.ndim}D")
print(f"test: {test_df.shape}, {test_df.ndim}D")

train: (874, 20), 2D
test: (1080, 8), 2D


In [44]:
train_df2 = pd.concat([train_en_df2, train_fr_df2, train_id_df2, train_tl_df2], axis=1)
test_df2 = pd.concat([test_en_df2, test_fr_df2, test_id_df2, test_tl_df2], axis=1)
# label_sr = pd.Series(['en', 'fr', 'id', 'tl'])

print(f"train: {train_df2.shape}, {train_df2.ndim}D")
print(f"test: {test_df2.shape}, {test_df2.ndim}D")

train: (1490, 4), 2D
test: (1770, 4), 2D


In [45]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 874 entries, 0 to 873
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   train_en_1  175 non-null    object
 1   train_en_2  180 non-null    object
 2   train_en_3  92 non-null     object
 3   train_en_4  168 non-null    object
 4   train_en_5  124 non-null    object
 5   train_fr_1  241 non-null    object
 6   train_fr_2  172 non-null    object
 7   train_fr_3  168 non-null    object
 8   train_fr_4  143 non-null    object
 9   train_fr_5  192 non-null    object
 10  train_id_1  40 non-null     object
 11  train_id_2  107 non-null    object
 12  train_id_3  232 non-null    object
 13  train_id_4  237 non-null    object
 14  train_id_5  874 non-null    object
 15  train_tl_1  309 non-null    object
 16  train_tl_2  204 non-null    object
 17  train_tl_3  174 non-null    object
 18  train_tl_4  215 non-null    object
 19  train_tl_5  225 non-null    object
dtypes: object(

In [46]:
train_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1490 entries, 0 to 1489
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   train_en  739 non-null    object
 1   train_fr  916 non-null    object
 2   train_id  1490 non-null   object
 3   train_tl  1127 non-null   object
dtypes: object(4)
memory usage: 46.7+ KB


In [47]:
train_df.isna().sum()

train_en_1    699
train_en_2    694
train_en_3    782
train_en_4    706
train_en_5    750
train_fr_1    633
train_fr_2    702
train_fr_3    706
train_fr_4    731
train_fr_5    682
train_id_1    834
train_id_2    767
train_id_3    642
train_id_4    637
train_id_5      0
train_tl_1    565
train_tl_2    670
train_tl_3    700
train_tl_4    659
train_tl_5    649
dtype: int64

In [48]:
train_df2.isna().sum()

train_en    751
train_fr    574
train_id      0
train_tl    363
dtype: int64

In [135]:
test_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1770 entries, 0 to 1769
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   test_en  1770 non-null   object
 1   test_fr  1101 non-null   object
 2   test_id  529 non-null    object
 3   test_tl  321 non-null    object
dtypes: object(4)
memory usage: 55.4+ KB


In [134]:
test_df2.isna().sum()

test_en       0
test_fr     669
test_id    1241
test_tl    1449
dtype: int64

- 결측치는 무시하자..
- unicode를 이용하는 방법으로 진행 ㄱㄱ

In [172]:
# data를 unicode 값으로 변환해주는 함수
def count_uni(col):
    carry = []
    
    for i in range(len(col)):
        word = col[i]
        # counter = np.zeros(65535)
        counter = 0   # unicode 한 평면이 가지는 크기: 65535
        
        if type(word) == str:
            # print(word)
            for j in range(len(word)):
                code_point = ord(word[j])
                # print(code_point)
                # counter[code_point] += 1
                counter += code_point
                # print(counter)
                
            # frequency
            # counter = counter / len(word)
            carry.append(counter/len(word))
            # carry.append(counter)
        else:
            carry.append(0)
        
        # print(counter)
    return carry

In [173]:
train_en_uni = count_uni(train_df2['train_en'])
train_fr_uni = count_uni(train_df2['train_fr'])
train_id_uni = count_uni(train_df2['train_id'])
train_tl_uni = count_uni(train_df2['train_tl'])

train_uni = pd.DataFrame(columns=['en', 'fr', 'id', 'tl'])

train_uni['en'] = train_en_uni
train_uni['fr'] = train_fr_uni
train_uni['id'] = train_id_uni
train_uni['tl'] = train_tl_uni

train_uni = train_uni.iloc[:550, :]    #... test에 맞춰야하는 구나..
train_uni = train_uni.T

In [174]:
test_en_uni = count_uni(test_df2['test_en'])
test_fr_uni = count_uni(test_df2['test_fr'])
test_id_uni = count_uni(test_df2['test_id'])
test_tl_uni = count_uni(test_df2['test_tl'])

test_uni = pd.DataFrame(columns=['en', 'fr', 'id', 'tl'])

test_uni['en'] = test_en_uni
test_uni['fr'] = test_fr_uni
test_uni['id'] = test_id_uni
test_uni['tl'] = test_tl_uni

test_uni = test_uni.iloc[:550, :]   # GaussianNB의 크기제한... en 때문에 너무 많은 결측치를 좀 줄일수 있을까...
test_uni = test_uni.T

In [175]:
from sklearn.tree import DecisionTreeClassifier

In [176]:
# model instance
dtc_model = DecisionTreeClassifier()
dtc_model.fit(train_uni, label_sr)

DecisionTreeClassifier()

In [177]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [178]:
dtc_pred = dtc_model.predict(test_uni)

In [179]:
dtc_acc = accuracy_score(label_sr, dtc_pred)
# dtc_prec = precision_score(label_sr, dtc_pred)
# dtc_recal = recall_score(label_sr, dtc_pred)
dtc_mat = confusion_matrix(label_sr, dtc_pred)
dtc_repot = classification_report(label_sr, dtc_pred, zero_division=0.0)

In [180]:
dtc_train_score = dtc_model.score(train_uni, label_sr)
dtc_test_score = dtc_model.score(test_uni, label_sr)

In [181]:
print(f"Decision Tree Accuracy: {dtc_acc*100:.2f} %")
print(f"Decision Tree Train Score: {dtc_train_score*100:.2f} %")
print(f"Decision Tree Test Score: {dtc_test_score*100:.2f} %\n")
print(f"Decision Tree Confusion Matrix\n{dtc_mat}\n")
print(f"Decision Tree Report\n{dtc_repot}")

Decision Tree Accuracy: 50.00 %
Decision Tree Train Score: 100.00 %
Decision Tree Test Score: 50.00 %

Decision Tree Confusion Matrix
[[0 0 1 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]]

Decision Tree Report
              precision    recall  f1-score   support

          en       0.00      0.00      0.00         1
          fr       1.00      1.00      1.00         1
          id       0.00      0.00      0.00         1
          tl       0.50      1.00      0.67         1

    accuracy                           0.50         4
   macro avg       0.38      0.50      0.42         4
weighted avg       0.38      0.50      0.42         4



- 이거 데이터 shape를 550개의 칼럼이 아닌 행으로 한다면 좀 달라지려나?